"""The parts of `playtest-youtube` that hold without a network: bundle resolution, the kit fallback, the request body, the audit warning, the credential paths, and the `.env` loader. Everything that talks to Google lives behind `load_credentials` / `upload_video` and is not exercised here."""

import json
import os
import tempfile
import unittest
from pathlib import Path

from playtest_pipeline import youtube_auth as auth
from playtest_pipeline import youtube_upload as up
from playtest_pipeline.youtube_cli import load_dotenv

REPORT_DATA = {
    "session": {"id": "s1", "title": "Golden Path", "date": "2026-08-27T16:13:19.000Z", "originalDurationMs": 428_000},
    "video": {"file": "condensed.mp4", "kind": "condensed", "durationMs": 188_000},
    "notes": [
        {"id": "n1", "label": "mark", "videoMs": 21_000, "text": "The lighting is too dark in the cave."},
        {"id": "n2", "label": "issue", "videoMs": 59_000, "text": "Pathfinding gets stuck on the bridge."},
        {"id": "n3", "label": "speech", "videoMs": 92_000, "text": "Boss music is far too loud here."},
    ],
    "cutmap": [],
}


def bundle(root: Path, *, kit: bool = True, video: bool = True, kind: str = "condensed") -> Path:
    report = root / "report"
    report.mkdir(parents=True, exist_ok=True)
    data = json.loads(json.dumps(REPORT_DATA))
    data["video"]["kind"] = kind
    (report / "report_data.json").write_text(json.dumps(data), encoding="utf-8")
    if video:
        (report / "condensed.mp4").write_bytes(b"\0" * 1024)
    if kit:
        kit_dir = report / "youtube"
        kit_dir.mkdir(exist_ok=True)
        (kit_dir / "title.txt").write_text("Kit title — playtest 2026-08-27\n", encoding="utf-8")
        (kit_dir / "description.txt").write_text("3 notes\n\n0:00 Session start\n0:21 MARK — one\n0:59 ISSUE — two\n\nGenerated by Playtest Recorder\n", encoding="utf-8")
    return report


class TestResolve(unittest.TestCase):
    def test_accepts_report_dir_or_session_dir(self):
        with tempfile.TemporaryDirectory() as tmp:
            report = bundle(Path(tmp))
            self.assertEqual(up.resolve_report_dir(report), report)
            self.assertEqual(up.resolve_report_dir(Path(tmp)), report)

    def test_rejects_a_directory_with_no_bundle(self):
        with tempfile.TemporaryDirectory() as tmp:
            with self.assertRaises(up.UploadError) as ctx:
                up.resolve_report_dir(Path(tmp))
            self.assertIn("process", ctx.exception.hint)

    def test_video_override_and_missing_condensed(self):
        with tempfile.TemporaryDirectory() as tmp:
            report = bundle(Path(tmp), video=False, kind="original")
            with self.assertRaises(up.UploadError) as ctx:
                up.resolve_video(report)
            self.assertIn("--video", ctx.exception.hint)
            other = Path(tmp) / "raw.mp4"
            other.write_bytes(b"\0")
            self.assertEqual(up.resolve_video(report, str(other)), other.resolve())


class TestKit(unittest.TestCase):
    def test_prefers_the_kit_files(self):
        with tempfile.TemporaryDirectory() as tmp:
            kit = up.read_kit(bundle(Path(tmp)))
            self.assertEqual(kit.source, "kit files")
            self.assertEqual(kit.title, "Kit title — playtest 2026-08-27")
            self.assertEqual(kit.chapter_count, 3)

    def test_rebuilds_from_report_data_when_the_kit_is_missing(self):
        with tempfile.TemporaryDirectory() as tmp:
            kit = up.read_kit(bundle(Path(tmp), kit=False))
            self.assertEqual(kit.source, "report_data.json")
            self.assertTrue(kit.title.startswith("Golden Path"))
            self.assertIn("0:00 Session start", kit.description)
            self.assertEqual(kit.chapter_count, 4)  # 0:00 + the three notes


class TestBody(unittest.TestCase):
    def body(self, **kwargs):
        kit = up.Kit("A title", "0:00 Session start", "test", Path("."))
        return up.build_body(kit, **kwargs)

    def test_defaults_are_the_unlisted_embeddable_carrier(self):
        body = self.body()
        self.assertEqual(body["status"], {"privacyStatus": "unlisted", "embeddable": True, "selfDeclaredMadeForKids": False})
        self.assertEqual(body["snippet"]["categoryId"], up.CATEGORY_GAMING)
        self.assertEqual(body["snippet"]["title"], "A title")

    def test_unknown_privacy_is_refused(self):
        with self.assertRaises(up.UploadError):
            self.body(privacy="secret")


class TestAuditWarning(unittest.TestCase):
    def test_silent_only_once_passed(self):
        self.assertIsNone(up.audit_warning("passed 2026-09-01"))
        self.assertIsNone(up.audit_warning("PASSED"))
        for status in (None, "", "requested 2026-08-28"):
            self.assertIn("PRIVATE", up.audit_warning(status) or "")


class TestUrlFile(unittest.TestCase):
    def test_round_trip(self):
        with tempfile.TemporaryDirectory() as tmp:
            report = bundle(Path(tmp))
            self.assertIsNone(up.read_url(report))
            written = up.write_url(report, "https://youtu.be/abc123")
            self.assertEqual(written, report / "youtube" / "url.txt")
            self.assertEqual(up.read_url(report), "https://youtu.be/abc123")


class TestCredentialPaths(unittest.TestCase):
    def test_config_dir_override(self):
        with tempfile.TemporaryDirectory() as tmp:
            os.environ[auth.CONFIG_DIR_ENV_VAR] = tmp
            try:
                self.assertEqual(auth.config_dir(), Path(tmp))
                self.assertEqual(auth.client_json_path().name, auth.CLIENT_JSON_NAME)
                self.assertEqual(auth.token_json_path().name, auth.TOKEN_JSON_NAME)
            finally:
                del os.environ[auth.CONFIG_DIR_ENV_VAR]

    def test_web_app_client_is_named_as_the_mistake(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "client.json"
            path.write_text(json.dumps({"web": {"client_id": "x", "client_secret": "y"}}), encoding="utf-8")
            with self.assertRaises(auth.AuthError) as ctx:
                auth.read_client(path)
            self.assertIn("Desktop app", ctx.exception.hint)

    def test_desktop_client_is_accepted(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "client.json"
            path.write_text(json.dumps({"installed": {"client_id": "id", "client_secret": "secret"}}), encoding="utf-8")
            self.assertEqual(auth.read_client(path)["client_id"], "id")

    def test_missing_client_points_at_the_wizard(self):
        with tempfile.TemporaryDirectory() as tmp:
            with self.assertRaises(auth.AuthError) as ctx:
                auth.read_client(Path(tmp) / "nope.json")
            self.assertIn("wizard", ctx.exception.hint)

    def test_token_info_reads_scopes_and_expiry(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "token.json"
            self.assertFalse(auth.read_token(path).exists)
            path.write_text(json.dumps({"refresh_token": "r", "scopes": auth.SCOPES, "expiry": "2020-01-01T00:00:00Z"}), encoding="utf-8")
            info = auth.read_token(path)
            self.assertTrue(info.exists and info.has_refresh_token and info.scopes_ok and info.expired)
            self.assertTrue(auth.forget_token(path))
            self.assertFalse(auth.forget_token(path))


class TestDotEnv(unittest.TestCase):
    def test_walks_up_quotes_and_never_clobbers_the_environment(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / ".env").write_text('# comment\nYOUTUBE_AUDIT_STATUS="passed 2026-09-01"\nNOTION_TOKEN=keep\n', encoding="utf-8")
            nested = root / "a" / "b"
            nested.mkdir(parents=True)
            env = {"NOTION_TOKEN": "already set"}
            found = load_dotenv(nested, env)
            self.assertEqual(found, root / ".env")
            self.assertEqual(env["YOUTUBE_AUDIT_STATUS"], "passed 2026-09-01")
            self.assertEqual(env["NOTION_TOKEN"], "already set")


if __name__ == "__main__":
    unittest.main()
