#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
# Windows goes through PowerShell's Start-Process, not explorer.exe: explorer
# only hands a URL to the shell when it cannot read it as a path (otherwise it
# just opens a folder window), and it exits 1 either way, so its status can
# never tell success from failure.
open_url() {
  local url="$1" ok=1
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  if   command -v wslview        >/dev/null 2>&1; then wslview "$url"  >/dev/null 2>&1 && ok=0 || true
  elif command -v powershell.exe >/dev/null 2>&1; then
    URL="$url" WSLENV=URL powershell.exe -NoProfile -NonInteractive -Command 'Start-Process $env:URL' >/dev/null 2>&1 && ok=0 || true
  elif command -v xdg-open       >/dev/null 2>&1; then xdg-open "$url" >/dev/null 2>&1 && ok=0 || true
  elif command -v open           >/dev/null 2>&1; then open "$url"     >/dev/null 2>&1 && ok=0 || true
  fi
  [[ "$ok" -eq 0 ]] || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '\n  %s%s⏎ %s%s ' "$BOLD" "$GREEN" "${1:-Nothing else to do here — press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# ── Windows: hand over from WSL to Git Bash ───────────────────────────────
# In PowerShell, `bash` is WSL's bash.exe: it cannot run Windows node/python
# and has no cygpath. When the script lives on a Windows drive and Git Bash
# exists, re-launch there so the wizard sees the same toolchain the user does.
_SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
if grep -qi microsoft /proc/version 2>/dev/null && [[ "$_SELF" == /mnt/[a-z]/* ]]; then
  for _gb in "/mnt/c/Program Files/Git/bin/bash.exe" "/mnt/c/Program Files (x86)/Git/bin/bash.exe"; do
    if [[ -x "$_gb" ]]; then
      _win_self=$(wslpath -w "$_SELF")
      printf '  (WSL bash detected — re-launching under Git Bash)\n'
      exec "$_gb" "$_win_self" "$@"
    fi
  done
  printf '  WSL bash cannot see the Windows toolchain and Git Bash was not found.\n'
  printf '  Run this from Git Bash instead:  "C:\\Program Files\\Git\\bin\\bash.exe" %s\n' "$(wslpath -w "$_SELF")"
  exit 1
fi

# to_unix PATH / to_win PATH convert between Windows and POSIX forms on
# Git Bash / WSL; pass-through elsewhere. Test files with to_unix, show
# paths to the human with to_win.
to_unix() {
  if   command -v cygpath >/dev/null 2>&1; then cygpath -u "$1"
  elif command -v wslpath >/dev/null 2>&1 && [[ "$1" == ?:* ]]; then wslpath -u "$1"
  else printf '%s' "$1"; fi
}
to_win() {
  if   command -v cygpath >/dev/null 2>&1; then cygpath -w "$1"
  elif command -v wslpath >/dev/null 2>&1; then wslpath -w "$1" 2>/dev/null || printf '%s' "$1"
  else printf '%s' "$1"; fi
}

# run_step "what" cmd args… runs a command with its output visible. On failure
# offers retry / skip / abort instead of exiting. Returns 0 on success or
# skip (SKIPPED records the skip), and exits only when the human says abort.
run_step() {
  local what="$1"; shift
  while :; do
    printf '  %s▶ %s%s\n' "$BLUE" "$what" "$RESET"
    if "$@"; then return 0; fi
    warn "'$what' failed."
    local reply=""
    printf '  %s? [r]etry / [s]kip / [a]bort%s ' "$YELLOW" "$RESET"
    read -r reply || true
    case "$reply" in
      s|S) SKIPPED+=("$what"); return 0 ;;
      a|A) printf '  aborted — re-run the wizard to resume.\n'; exit 1 ;;
    esac
  done
}

# require_file PATH "how to make it" loops until PATH exists: runs the maker
# command when given (make_cmd…), otherwise asks the human to create it.
#   require_file "$KIT/description.txt" "generate the kit" python -m … youtube-kit "$S"
require_file() {
  local path="$1" how="$2"; shift 2
  until [[ -e "$path" ]]; do
    warn "missing: $(to_win "$path")"
    if (( $# )); then run_step "$how" "$@"; [[ -e "$path" ]] && break; fi
    say "$how, then press Enter to check again."
    pause
  done
}

# require_cmd NAME "how to install" loops until NAME is on PATH.
require_cmd() {
  until command -v "$1" >/dev/null 2>&1; do
    warn "'$1' is not on PATH. $2"
    pause "Installed? Press Enter to check again."
  done
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: PLAN.md M2.3 — live verification of the YouTube carrier.
#
#   bash verification/wizards/wizard-m2.3-youtube-live.sh [<session dir or report dir>]
#
# Default target is REPORT_BIG (m1-live). Values captured:
#   NOTION_TOKEN, PARENT_ID → .env (asked only if missing)
#   YOUTUBE_URL             → <report>/youtube/url.txt   (the unlisted upload)
#   NOTION_URL + 4 results  → verification/evidence/m2/m2.3-result.txt
# The wizard never gives up on a recoverable state: it generates what is
# missing, asks for what it cannot make, and retries commands on request.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_DIR"
RESULT_FILE="$REPO_DIR/verification/evidence/m2/m2.3-result.txt"
DEFAULT_TARGET='C:\Users\George\Videos\PlaytestSessions\2026-08-23_114134_m1-live'

# to_clip TEXT copies to the Windows clipboard when clip.exe exists.
to_clip() {
  if command -v clip.exe >/dev/null 2>&1; then printf '%s' "$1" | clip.exe && note "(copied to clipboard)"; fi
}

# resolve_report DIR → sets REPORT (…/report) when DIR is a session or report
# dir holding report_data.json; returns 1 otherwise.
resolve_report() {
  local d; d="$(to_unix "$1")"
  if   [[ -f "$d/report/report_data.json" ]]; then REPORT="$d/report"
  elif [[ -f "$d/report_data.json" ]];        then REPORT="$d"
  else return 1; fi
}

banner "M2.3 — YouTube carrier, live check"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight: report bundle, YouTube kit, publisher build, Notion credentials"
require_cmd node   "Install Node.js 20+ (https://nodejs.org) — the publisher runs on it."
require_cmd python "Install Python 3.11+ (https://python.org) — the pipeline runs on it."

TARGET="${1:-$DEFAULT_TARGET}"
until resolve_report "$TARGET"; do
  d="$(to_unix "$TARGET")"
  if [[ -f "$d/session.json" || -f "$d/session.journal.jsonl" ]]; then
    warn "$(to_win "$d") is a session without a report bundle."
    say "Running the pipeline on it now (needs the OBS recording; add --recording if it moved):"
    run_step "playtest-pipeline process" python -m playtest_pipeline.cli process "$d"
    resolve_report "$TARGET" && break
  else
    warn "no report bundle at $(to_win "$d")"
  fi
  say "Paste the session folder (e.g. $DEFAULT_TARGET) or its report\\ subfolder:"
  ask TARGET "Session or report dir:"
done
SESSION_DIR="$(dirname "$REPORT")"
KIT="$REPORT/youtube"
WIN_REPORT="$(to_win "$REPORT")"
say "${GREEN}✓${RESET} report bundle: $WIN_REPORT"

require_file "$REPORT/condensed.mp4" "re-run the pipeline so condensed.mp4 exists" \
  python -m playtest_pipeline.cli process "$SESSION_DIR"
require_file "$KIT/description.txt" "generate the YouTube kit" \
  python -m playtest_pipeline.cli youtube-kit "$SESSION_DIR"
say "${GREEN}✓${RESET} condensed.mp4 + youtube kit"

require_file "packages/notion-publisher/dist/cli.js" "build the Notion publisher" \
  npm run build -w @playtest/notion-publisher
say "${GREEN}✓${RESET} publisher built"

# Notion credentials: ask for what is missing instead of warning about it.
if ! grep -qE '^NOTION_TOKEN=.+' .env 2>/dev/null; then
  printf '\n'; say "Stage 4 publishes to Notion, so we need the integration token now."
  open_url "https://www.notion.so/profile/integrations"
  step "Open your integration (or New integration → Internal) → Configuration → copy the Internal Integration Secret (ntn_…)."
  until [[ "${NOTION_TOKEN:-}" == ntn_* || "${NOTION_TOKEN:-}" == secret_* ]]; do
    ask_secret NOTION_TOKEN "Paste the integration secret:"
    [[ "$NOTION_TOKEN" == ntn_* || "$NOTION_TOKEN" == secret_* ]] || warn "expected a value starting with ntn_ (or secret_)"
  done
  write_env NOTION_TOKEN "$NOTION_TOKEN"
fi
if ! grep -qE '^PARENT_ID=.+' .env 2>/dev/null; then
  step "Open the Notion page that will hold the reports → ··· → Connections → add the integration."
  step "Copy the page URL: the 32 hex chars at its end are the page id."
  until [[ "${PARENT_ID:-}" =~ ^[0-9a-fA-F]{32}$ ]]; do
    ask PARENT_ID "Paste the page URL or id:"
    PARENT_ID="$(printf '%s' "$PARENT_ID" | grep -oE '[0-9a-fA-F]{32}' | tail -n1 || true)"
    [[ "${PARENT_ID:-}" =~ ^[0-9a-fA-F]{32}$ ]] || warn "couldn't find a 32-hex page id in that"
  done
  write_env PARENT_ID "$PARENT_ID"
fi
say "${GREEN}✓${RESET} .env has NOTION_TOKEN + PARENT_ID"

printf '\n'; say "${BOLD}Title:${RESET}"; sed 's/^/    /' "$KIT/title.txt"
printf '\n'; say "${BOLD}Description (chapter list):${RESET}"; sed 's/^/    /' "$KIT/description.txt"; printf '\n'
chapter_count=$(grep -cE '^[0-9]+:[0-9]{2}' "$KIT/description.txt" || true)
if (( chapter_count >= 3 )); then say "$chapter_count chapters → YouTube should show a chapter bar."
else warn "$chapter_count chapter line(s) — expect plain timestamps, no chapter bar (by design)."; fi
pause "All checks passed; nothing to do in this stage. Press Enter to open YouTube Studio (stage 2)."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "YouTube Studio: upload condensed.mp4 as UNLISTED"
if [[ -s "$KIT/url.txt" ]]; then
  say "A previous run saved: $(cat "$KIT/url.txt")"
  confirm "Reuse that upload (skip uploading again)?" && YOUTUBE_URL="$(cat "$KIT/url.txt")"
fi
if [[ -z "${YOUTUBE_URL:-}" ]]; then
  open_url "https://studio.youtube.com/"
  step "Sign in if asked. Top right: Create → Upload videos."
  step "Drop this file on the dialog:  $WIN_REPORT\\condensed.mp4"
  to_clip "$(cat "$KIT/title.txt")"
  step "Details → Title: select the default title and paste (clipboard = title.txt)."
  pause "Press Enter once the title is pasted (the clipboard will then switch to the description)."
  to_clip "$(cat "$KIT/description.txt")"
  step "Details → Description: paste (clipboard = description.txt — the timestamps become chapters)."
  step "Scroll down → Audience: 'No, it's not made for kids'."
  step "Next (Video elements) → Next (Checks) → Visibility: ${BOLD}Unlisted${RESET} → Save."
  step "The 'Video published' dialog shows the link (https://youtu.be/…): click the copy icon."
fi
until YT_ID=$(node -e "import('./packages/notion-publisher/dist/blocks.js').then(m=>console.log(m.parseYouTubeId(process.argv[1]))).catch(()=>process.exit(1))" "${YOUTUBE_URL:-}" 2>/dev/null); do
  [[ -n "${YOUTUBE_URL:-}" ]] && warn "'$YOUTUBE_URL' is not a YouTube link or 11-char id."
  ask YOUTUBE_URL "Paste the youtu.be link:"
done
printf '%s\n' "https://youtu.be/$YT_ID" > "$KIT/url.txt"
printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "$(to_win "$KIT/url.txt")"
pause "Press Enter to open the watch page and check the chapter bar (stage 3)."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "YouTube watch page: processing + chapter bar"
say "YouTube processes SD first, HD a few minutes later; chapters can lag processing by a few minutes."
open_url "https://www.youtube.com/watch?v=$YT_ID"
step "Wait until the video plays."
step "Hover the progress bar: it should be split into $chapter_count segments named after the notes;"
step "the current chapter title also shows next to the time readout under the player."
CHAPTERS_OK=no
until [[ "$CHAPTERS_OK" == yes ]]; do
  if confirm "Chapter bar visible with the note titles?"; then CHAPTERS_OK=yes; break; fi
  warn "Checklist: description starts with 0:00? every gap ≥ 10 s? ≥ 3 timestamps? Reload after a few minutes."
  say "You can also open Studio → the video → Details and re-check the description survived the paste."
  confirm "Keep waiting and re-check? (n = record 'no' and move on)" || break
done

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Publish the Notion page with --youtube"
say "Running:  npx playtest-notion publish \"$WIN_REPORT\" --youtube https://youtu.be/$YT_ID"
printf '\n'
PUBLISH_LOG_FILE="$(mktemp)"
publish_once() { node packages/notion-publisher/dist/cli.js publish "$REPORT" --youtube "https://youtu.be/$YT_ID" 2>&1 | tee "$PUBLISH_LOG_FILE"; return "${PIPESTATUS[0]}"; }
run_step "playtest-notion publish" publish_once
NOTION_URL=$(sed -nE 's/^Published: (https?:[^ ]+).*/\1/p' "$PUBLISH_LOG_FILE" | tail -n1)
until [[ "${NOTION_URL:-}" == https://* ]]; do
  say "Couldn't parse the page URL from the output above."
  ask NOTION_URL "Paste the 'Published:' URL (or the page URL from Notion):"
done
printf '\n'; say "Block dump (expect a line:  video [external] https://www.youtube.com/watch?v=$YT_ID):"
node verification/notion/notion-page-dump.mjs "$NOTION_URL" 2>&1 | sed 's/^/    /' | head -20 || warn "page dump failed (non-fatal — check the page by eye in the next stage)"
pause "Press Enter to open the Notion page for the three render checks (stage 5)."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Notion page: the three render checks"
open_url "$NOTION_URL"
step "(1) The video block shows the YouTube player and PLAYS (click play)."
if confirm "Unlisted video renders and plays inside the API-created video block?"; then RENDER_OK=yes; else
  RENDER_OK=no
  warn "'Video unavailable'? Isolate the cause: YouTube Studio → Content → the video → Visibility: Public, then reload the Notion page."
  if confirm "Does it render when Public?"; then RENDER_OK="no (unlisted) / yes (public)"; else RENDER_OK="no (even public)"; fi
  say "Set the video back to Unlisted afterwards."
  pause "Press Enter once it is back to Unlisted."
fi
step "(2) Click the first linked note timestamp, e.g. [0:19]: YouTube must open AT that time (not at 0:00)."
if confirm "Deep link honored (?t= lands at the right second)?"; then DEEPLINK_OK=yes; else DEEPLINK_OK=no; fi
step "(3) Back on the Notion page, hover the embedded player's progress bar: chapters visible there too?"
if confirm "Chapters visible in the embedded player?"; then EMBED_CHAPTERS_OK=yes; else EMBED_CHAPTERS_OK=no; fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Record the outcome + tidy"
mkdir -p "$(dirname "$RESULT_FILE")"
{
  printf 'M2.3 live check — %s\n' "$(date +%Y-%m-%d)"
  printf 'report:            %s\n' "$WIN_REPORT"
  printf 'youtube:           https://youtu.be/%s (unlisted)\n' "$YT_ID"
  printf 'notion page:       %s\n' "$NOTION_URL"
  printf 'chapter bar (yt):  %s\n' "$CHAPTERS_OK"
  printf 'unlisted renders:  %s\n' "$RENDER_OK"
  printf '&t= honored:       %s\n' "$DEEPLINK_OK"
  printf 'chapters in embed: %s\n' "$EMBED_CHAPTERS_OK"
} > "$RESULT_FILE"
printf '  %s✓ wrote%s %s\n\n' "$GREEN" "$RESET" "$(to_win "$RESULT_FILE")"
RISK_LINE="verified live $(date +%Y-%m-%d): unlisted video in an API-created video block renders: $RENDER_OK; &t= honored: $DEEPLINK_OK; chapter bar on the watch page: $CHAPTERS_OK, in the embed: $EMBED_CHAPTERS_OK"
say "Risk-9 line for the tech-stack report (c) and the PLAN risk table:"
printf '    %s\n' "$RISK_LINE"; to_clip "$RISK_LINE"
printf '\n'
if confirm "Archive the older test pages under PARENT_ID now (m1-live / m5-live / stress)?"; then
  say "Paste each page URL to archive; empty line when done."
  while :; do
    ask OLD_PAGE "Page URL to archive (Enter = done):"
    [[ -z "$OLD_PAGE" ]] && break
    run_step "archive $OLD_PAGE" node verification/notion/notion-page-dump.mjs "$OLD_PAGE" --archive
    OLD_PAGE=""
  done
fi
note "Next for Claude: paste the risk-9 line into the docs and delete M2.3 from PLAN.md (completed items are removed, not ticked)."
pause "Done. Press Enter for the summary."

finish
