#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '\n  %s%s⏎ %s%s ' "$BOLD" "$GREEN" "${1:-Nothing else to do here — press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# ── Windows: hand over from WSL to Git Bash ───────────────────────────────
# In PowerShell, `bash` is WSL's bash.exe: it cannot run Windows node/python
# and has no cygpath. When the script lives on a Windows drive and Git Bash
# exists, re-launch there so the wizard sees the same toolchain the user does.
_SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
if grep -qi microsoft /proc/version 2>/dev/null && [[ "$_SELF" == /mnt/[a-z]/* ]]; then
  for _gb in "/mnt/c/Program Files/Git/bin/bash.exe" "/mnt/c/Program Files (x86)/Git/bin/bash.exe"; do
    if [[ -x "$_gb" ]]; then
      _win_self=$(wslpath -w "$_SELF")
      printf '  (WSL bash detected — re-launching under Git Bash)\n'
      exec "$_gb" "$_win_self" "$@"
    fi
  done
  printf '  WSL bash cannot see the Windows toolchain and Git Bash was not found.\n'
  printf '  Run this from Git Bash instead:  "C:\\Program Files\\Git\\bin\\bash.exe" %s\n' "$(wslpath -w "$_SELF")"
  exit 1
fi

# to_unix PATH / to_win PATH convert between Windows and POSIX forms on
# Git Bash / WSL; pass-through elsewhere. Test files with to_unix, show
# paths to the human with to_win.
to_unix() {
  if   command -v cygpath >/dev/null 2>&1; then cygpath -u "$1"
  elif command -v wslpath >/dev/null 2>&1 && [[ "$1" == ?:* ]]; then wslpath -u "$1"
  else printf '%s' "$1"; fi
}
to_win() {
  if   command -v cygpath >/dev/null 2>&1; then cygpath -w "$1"
  elif command -v wslpath >/dev/null 2>&1; then wslpath -w "$1" 2>/dev/null || printf '%s' "$1"
  else printf '%s' "$1"; fi
}

# run_step "what" cmd args… runs a command with its output visible. On failure
# offers retry / skip / abort instead of exiting. Returns 0 on success or
# skip (SKIPPED records the skip), and exits only when the human says abort.
run_step() {
  local what="$1"; shift
  while :; do
    printf '  %s▶ %s%s\n' "$BLUE" "$what" "$RESET"
    if "$@"; then return 0; fi
    warn "'$what' failed."
    local reply=""
    printf '  %s? [r]etry / [s]kip / [a]bort%s ' "$YELLOW" "$RESET"
    read -r reply || true
    case "$reply" in
      s|S) SKIPPED+=("$what"); return 0 ;;
      a|A) printf '  aborted — re-run the wizard to resume.\n'; exit 1 ;;
    esac
  done
}

# require_file PATH "how to make it" loops until PATH exists: runs the maker
# command when given (make_cmd…), otherwise asks the human to create it.
#   require_file "$KIT/description.txt" "generate the kit" python -m … youtube-kit "$S"
require_file() {
  local path="$1" how="$2"; shift 2
  until [[ -e "$path" ]]; do
    warn "missing: $(to_win "$path")"
    if (( $# )); then run_step "$how" "$@"; [[ -e "$path" ]] && break; fi
    say "$how, then press Enter to check again."
    pause
  done
}

# require_cmd NAME "how to install" loops until NAME is on PATH.
require_cmd() {
  until command -v "$1" >/dev/null 2>&1; do
    warn "'$1' is not on PATH. $2"
    pause "Installed? Press Enter to check again."
  done
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: PLAN.md M2.4 — prepare the (opt-in) YouTube API uploader.
#
#   bash verification/wizards/wizard-m2.4-youtube-api.sh
#
# Google Cloud project → YouTube Data API v3 → OAuth consent screen (External,
# Testing) → Desktop OAuth client JSON → compliance audit request. Values:
#   YOUTUBE_PRIVACY_POLICY_URL, YOUTUBE_GCP_PROJECT, YOUTUBE_OAUTH_CLIENT_ID → .env (not secret)
#   client JSON (holds the client secret)  → %APPDATA%\playtest-recorder\youtube-client.json
#   YOUTUBE_AUDIT_STATUS                   → .env  (pending until Google replies)
# Nothing is sent to GitHub. Until the audit passes, EVERY API upload is
# locked private — the manual Studio upload stays the product path.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_DIR"

APPDATA_U="$(to_unix "${APPDATA:-$HOME/AppData/Roaming}")"
CLIENT_DIR="$APPDATA_U/playtest-recorder"
CLIENT_JSON="$CLIENT_DIR/youtube-client.json"
CLIENT_JSON_WIN="$(to_win "$CLIENT_JSON")"
SCOPE="https://www.googleapis.com/auth/youtube.upload"

banner "M2.4 — YouTube Data API uploader: Google Cloud + audit"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Privacy policy page (the audit and the consent screen both want one)"
say "Google requires a PUBLIC https page with a privacy policy that has a section on how"
say "YouTube data is used (here: 'the tool uploads the video you choose, unlisted, to your"
say "own channel; it reads nothing back and stores nothing'). GitHub Pages is enough."
if [[ ! -f docs/privacy.md ]]; then
  say "No docs/privacy.md in the repo yet — writing a starter you can publish with GitHub Pages:"
  mkdir -p docs
  cat > docs/privacy.md <<'PRIVACY'
# Playtest Recorder — Privacy Policy

Playtest Recorder is a desktop tool that records your own playtest sessions locally.
It does not collect analytics and has no server of its own.

## YouTube

When you choose to upload a session, Playtest Recorder uses the YouTube Data API
to upload the video file you selected to **your own** YouTube channel, with the
title and description you reviewed, as an **unlisted** video. It requests only
the `youtube.upload` permission, reads no data from your channel, and stores
nothing except the OAuth token on your own computer (`%APPDATA%\playtest-recorder`),
which you can delete at any time. Use of YouTube is subject to the
[YouTube Terms of Service](https://www.youtube.com/t/terms) and the
[Google Privacy Policy](https://policies.google.com/privacy). You can revoke the
tool's access at <https://myaccount.google.com/permissions>.

## Notion

If you publish a report to Notion, the notes and video link you reviewed are sent
to the Notion workspace you connected, using your own integration token.

## Contact

georgetw1108@gmail.com
PRIVACY
  printf '  %s✓ wrote%s docs/privacy.md — commit + push it, then enable Pages:\n' "$GREEN" "$RESET"
  open_url "https://github.com/gw1108/video-record-plus-notes/settings/pages"
  step "Build and deployment → Source: Deploy from a branch → Branch: main, folder: /docs → Save."
  step "After ~1 min the page is at https://gw1108.github.io/video-record-plus-notes/privacy"
  note "(If the repo name/owner differs, adjust the URL you paste below.)"
fi
until [[ "${YOUTUBE_PRIVACY_POLICY_URL:-}" =~ ^https:// ]]; do
  ask YOUTUBE_PRIVACY_POLICY_URL "Public https URL of the privacy policy:"
  [[ "$YOUTUBE_PRIVACY_POLICY_URL" =~ ^https:// ]] || warn "must start with https:// — Google rejects anything else"
done
write_env YOUTUBE_PRIVACY_POLICY_URL "$YOUTUBE_PRIVACY_POLICY_URL"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud: create the project"
open_url "https://console.cloud.google.com/projectcreate"
step "Sign in with the Google account that owns the YouTube channel."
step "Project name: playtest-recorder (any name). Note the generated Project ID shown under the name."
step "Create → wait for the notification → 'Select project'."
until [[ "${YOUTUBE_GCP_PROJECT:-}" =~ ^[a-z][a-z0-9-]{4,29}$ ]]; do
  ask YOUTUBE_GCP_PROJECT "Project ID (lowercase, e.g. playtest-recorder-123456):"
  [[ "$YOUTUBE_GCP_PROJECT" =~ ^[a-z][a-z0-9-]{4,29}$ ]] || warn "that doesn't look like a project ID (6–30 chars, lowercase letters, digits, hyphens)"
done
write_env YOUTUBE_GCP_PROJECT "$YOUTUBE_GCP_PROJECT"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Enable YouTube Data API v3"
open_url "https://console.cloud.google.com/apis/library/youtube.googleapis.com?project=$YOUTUBE_GCP_PROJECT"
step "Click Enable (if it says 'Manage', it is already enabled)."
note "Quota is a non-issue: videos.insert costs 1 unit of its own 100/day bucket."
pause "Press Enter once the API shows as enabled (stage 4 = consent screen)."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "OAuth consent screen: External, Testing, you as test user, upload scope"
note "Google moved this to 'Google Auth Platform' in 2025; if the page layout differs, the same"
note "four settings exist under Branding / Audience / Data access."
open_url "https://console.cloud.google.com/auth/overview?project=$YOUTUBE_GCP_PROJECT"
step "Get started → App name: Playtest Recorder; User support email: your Gmail → Next."
step "Audience: ${BOLD}External${RESET} → Next. Contact email: your Gmail → Next → agree → Create."
pause "Press Enter once the app is created."
open_url "https://console.cloud.google.com/auth/branding?project=$YOUTUBE_GCP_PROJECT"
step "Branding → App privacy policy link: $YOUTUBE_PRIVACY_POLICY_URL → Save."
pause "Press Enter once the privacy link is saved."
open_url "https://console.cloud.google.com/auth/audience?project=$YOUTUBE_GCP_PROJECT"
step "Audience → Publishing status stays ${BOLD}Testing${RESET}. Test users → Add users → your Gmail → Save."
warn "In Testing, every refresh token expires after 7 days → weekly re-consent for the uploader (accepted for a solo CLI)."
pause "Press Enter once your account is listed as a test user."
open_url "https://console.cloud.google.com/auth/scopes?project=$YOUTUBE_GCP_PROJECT"
to_clip "$SCOPE"
step "Data access → Add or remove scopes → 'Manually add scopes' → paste (clipboard = $SCOPE) → Add to table → Update → Save."
note "youtube.upload is a 'sensitive' scope: leaving Testing for Production would need Google's app verification."
pause "Press Enter once the scope is saved (stage 5 = OAuth client)."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "OAuth client (Desktop app) → $CLIENT_JSON_WIN"
if [[ -f "$CLIENT_JSON" ]] && node -e "const j=require(process.argv[1]);process.exit(j.installed&&j.installed.client_id?0:1)" "$CLIENT_JSON" 2>/dev/null; then
  say "${GREEN}✓${RESET} a Desktop-app client JSON is already at $CLIENT_JSON_WIN"
  if ! confirm "Replace it with a new client?"; then
    YOUTUBE_OAUTH_CLIENT_ID="$(node -p "require(process.argv[1]).installed.client_id" "$CLIENT_JSON")"
  fi
fi
if [[ -z "${YOUTUBE_OAUTH_CLIENT_ID:-}" ]]; then
  open_url "https://console.cloud.google.com/apis/credentials?project=$YOUTUBE_GCP_PROJECT"
  step "Create credentials → OAuth client ID → Application type: ${BOLD}Desktop app${RESET} → Name: playtest-recorder-cli → Create."
  step "In the 'OAuth client created' dialog: Download JSON (client_secret_….json lands in Downloads). Keep the dialog open."
  DOWNLOADS="$(to_unix "${USERPROFILE:-$HOME}")/Downloads"
  while :; do
    DL_DEFAULT="$(ls -t "$DOWNLOADS"/client_secret_*.json 2>/dev/null | head -n1 || true)"
    if [[ -n "$DL_DEFAULT" ]]; then say "Newest match in Downloads: $(to_win "$DL_DEFAULT")"; fi
    ask DOWNLOADED_JSON "Path of the downloaded JSON [Enter = newest client_secret_*.json in Downloads]:"
    [[ -z "$DOWNLOADED_JSON" ]] && DOWNLOADED_JSON="$DL_DEFAULT"
    DOWNLOADED_JSON="$(to_unix "${DOWNLOADED_JSON:-}")"
    if [[ ! -f "$DOWNLOADED_JSON" ]]; then warn "file not found: ${DOWNLOADED_JSON:-(none)} — download it, then try again"; DOWNLOADED_JSON=""; continue; fi
    if ! node -e "const j=require(process.argv[1]);process.exit(j.installed&&j.installed.client_id&&j.installed.client_secret?0:1)" "$DOWNLOADED_JSON" 2>/dev/null; then
      warn "that JSON has no installed.client_id/client_secret — it is not a Desktop-app client. Create one with type 'Desktop app' and download again."
      DOWNLOADED_JSON=""; continue
    fi
    break
  done
  mkdir -p "$CLIENT_DIR"
  mv -f "$DOWNLOADED_JSON" "$CLIENT_JSON"
  printf '  %s✓ moved%s → %s (holds the client secret; outside the repo, never commit it)\n' "$GREEN" "$RESET" "$CLIENT_JSON_WIN"
  YOUTUBE_OAUTH_CLIENT_ID="$(node -p "require(process.argv[1]).installed.client_id" "$CLIENT_JSON")"
fi
write_env YOUTUBE_OAUTH_CLIENT_ID "$YOUTUBE_OAUTH_CLIENT_ID"
pause "Press Enter to open the compliance-audit form (stage 6)."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Request the YouTube API Services compliance audit"
say "Without a passed audit, every videos.insert from this project is locked PRIVATE (no appeal),"
say "reportedly even with privacyStatus=unlisted — so do not build on the uploader until it passes."
open_url "https://support.google.com/youtube/contact/yt_api_form"
step "Fill the form with:"
say "    project ID:      $YOUTUBE_GCP_PROJECT"
say "    client ID:       $YOUTUBE_OAUTH_CLIENT_ID"
say "    privacy policy:  $YOUTUBE_PRIVACY_POLICY_URL"
say "    description:     'Desktop tool that uploads a playtest recording chosen by the user to the"
say "                      user's own channel as unlisted; reads nothing back; single-user CLI.'"
say "    demo access:     a short screen recording of the CLI is accepted."
note "The audit is free and typically takes weeks; Google replies by email."
pause "Press Enter once the audit form is submitted."
write_env YOUTUBE_AUDIT_STATUS "requested $(date +%Y-%m-%d)"
printf '\n'
say "When the approval email arrives: set YOUTUBE_AUDIT_STATUS=passed in .env, then ask Claude to build"
say "PLAN M2.4 step 3 (playtest-youtube upload) — it reads $CLIENT_JSON_WIN and caches"
say "tokens next to it as youtube-token.json. Until then keep using the manual upload (M2.3 wizard)."
pause "Done. Press Enter for the summary."

finish
