#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the $wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '\n  %s%s⏎ %s%s ' "$BOLD" "$GREEN" "${1:-Nothing else to do here — press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# ── Windows: hand over from WSL to Git Bash ───────────────────────────────
# In PowerShell, `bash` is WSL's bash.exe: it cannot run Windows node/python
# and has no cygpath. When the script lives on a Windows drive and Git Bash
# exists, re-launch there so the wizard sees the same toolchain the user does.
_SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
if grep -qi microsoft /proc/version 2>/dev/null && [[ "$_SELF" == /mnt/[a-z]/* ]]; then
  for _gb in "/mnt/c/Program Files/Git/bin/bash.exe" "/mnt/c/Program Files (x86)/Git/bin/bash.exe"; do
    if [[ -x "$_gb" ]]; then
      _win_self=$(wslpath -w "$_SELF")
      printf '  (WSL bash detected — re-launching under Git Bash)\n'
      exec "$_gb" "$_win_self" "$@"
    fi
  done
  printf '  WSL bash cannot see the Windows toolchain and Git Bash was not found.\n'
  printf '  Run this from Git Bash instead:  "C:\\Program Files\\Git\\bin\\bash.exe" %s\n' "$(wslpath -w "$_SELF")"
  exit 1
fi

# to_unix PATH / to_win PATH convert between Windows and POSIX forms on
# Git Bash / WSL; pass-through elsewhere. Test files with to_unix, show
# paths to the human with to_win.
to_unix() {
  if   command -v cygpath >/dev/null 2>&1; then cygpath -u "$1"
  elif command -v wslpath >/dev/null 2>&1 && [[ "$1" == ?:* ]]; then wslpath -u "$1"
  else printf '%s' "$1"; fi
}
to_win() {
  if   command -v cygpath >/dev/null 2>&1; then cygpath -w "$1"
  elif command -v wslpath >/dev/null 2>&1; then wslpath -w "$1" 2>/dev/null || printf '%s' "$1"
  else printf '%s' "$1"; fi
}

# run_step "what" cmd args… runs a command with its output visible. On failure
# offers retry / skip / abort instead of exiting. Returns 0 on success or
# skip (SKIPPED records the skip), and exits only when the human says abort.
run_step() {
  local what="$1"; shift
  while :; do
    printf '  %s▶ %s%s\n' "$BLUE" "$what" "$RESET"
    if "$@"; then return 0; fi
    warn "'$what' failed."
    local reply=""
    printf '  %s? [r]etry / [s]kip / [a]bort%s ' "$YELLOW" "$RESET"
    read -r reply || true
    case "$reply" in
      s|S) SKIPPED+=("$what"); return 0 ;;
      a|A) printf '  aborted — re-run the wizard to resume.\n'; exit 1 ;;
    esac
  done
}

# require_file PATH "how to make it" loops until PATH exists: runs the maker
# command when given (make_cmd…), otherwise asks the human to create it.
#   require_file "$KIT/description.txt" "generate the kit" python -m … youtube-kit "$S"
require_file() {
  local path="$1" how="$2"; shift 2
  until [[ -e "$path" ]]; do
    warn "missing: $(to_win "$path")"
    if (( $# )); then run_step "$how" "$@"; [[ -e "$path" ]] && break; fi
    say "$how, then press Enter to check again."
    pause
  done
}

# require_cmd NAME "how to install" loops until NAME is on PATH.
require_cmd() {
  until command -v "$1" >/dev/null 2>&1; do
    warn "'$1' is not on PATH. $2"
    pause "Installed? Press Enter to check again."
  done
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: PLAN.md M5 — clean-machine installer and release exit in Windows Sandbox.
#
#   bash verification/wizards/wizard-m5-windows-sandbox.sh
#
# Public, non-secret observations are saved under the run's ignored mapped-transfer directory. The dated outcome is written under verification/evidence/m5/. No credential is requested or written. The selected installer, wheel, helper check results, screenshots, and copied live session remain tied together by SHA-256 identities in kit-manifest.json.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_DIR"
INSTALLER="$REPO_DIR/apps/recorder/release/Playtest Recorder Setup 0.1.0.exe"
WHEEL="$REPO_DIR/pipeline/dist/playtest_pipeline-0.1.0-py3-none-win_amd64.whl"
CAPTURE_HELPER="$REPO_DIR/helper/capture-helper/target/release/capture-helper.exe"
SANDBOX_HELPER_SOURCE="$REPO_DIR/verification/wizards/m5-sandbox-checks.ps1"
TRANSFER_BASE="$REPO_DIR/verification/evidence/m5/.sandbox-transfer"
CURRENT_RUN_FILE="$TRANSFER_BASE/current-run.txt"
RUN_COMMAND='bash verification/wizards/wizard-m5-windows-sandbox.sh'
PYTHON_CMD=()
MANIFEST_HASH=""
WHEEL_FFMPEG_HASH=""
WHEEL_FFPROBE_HASH=""

select_python() {
  if command -v python >/dev/null 2>&1 && python -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 11) else 1)' >/dev/null 2>&1; then PYTHON_CMD=(python); return 0; fi
  if command -v py.exe >/dev/null 2>&1 && py.exe -3 -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 11) else 1)' >/dev/null 2>&1; then PYTHON_CMD=(py.exe -3); return 0; fi
  return 1
}

require_host_python() {
  until select_python; do
    warn "Python 3.11+ is needed only because the repository's current release-wheel builder needs it."
    open_url "https://www.python.org/downloads/windows/"
    step "Download the current Python 3.11+ Windows installer, run it, select Add python.exe to PATH, then return here."
    pause "Python installed on the host? Press Enter to check again."
  done
}

sha256_file() {
  local win_path; win_path="$(to_win "$1")"
  M5_HASH_PATH="$win_path" powershell.exe -NoProfile -Command '(Get-FileHash -LiteralPath $env:M5_HASH_PATH -Algorithm SHA256).Hash.ToLowerInvariant()' | tr -d '\r'
}

wheel_entry_sha256() {
  local entry="$1"
  M5_WHEEL_PATH="$(to_win "$WHEEL")" M5_WHEEL_ENTRY="$entry" powershell.exe -NoProfile -Command 'Add-Type -AssemblyName System.IO.Compression.FileSystem;$zip=[IO.Compression.ZipFile]::OpenRead($env:M5_WHEEL_PATH);try{$entry=$zip.Entries|Where-Object FullName -eq $env:M5_WHEEL_ENTRY|Select-Object -First 1;if(-not $entry){exit 1};$stream=$entry.Open();$sha=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($sha.ComputeHash($stream))).Replace("-","").ToLowerInvariant()}finally{$sha.Dispose();$stream.Dispose()}}finally{$zip.Dispose()}' | tr -d '\r'
}

validate_installer() {
  [[ -s "$INSTALLER" && -s "$CAPTURE_HELPER" ]] || return 1
  [[ $(wc -c < "$INSTALLER") -gt 1000000 ]] || return 1
  if find apps/recorder/src apps/recorder/package.json apps/recorder/resources packages/shared/src package-lock.json "$CAPTURE_HELPER" -type f -newer "$INSTALLER" -print -quit 2>/dev/null | grep -q .; then return 1; fi
  M5_INSTALLER_PATH="$(to_win "$INSTALLER")" powershell.exe -NoProfile -Command '$item=Get-Item -LiteralPath $env:M5_INSTALLER_PATH; if ($item.VersionInfo.ProductName -ne "Playtest Recorder" -or $item.VersionInfo.ProductVersion -ne "0.1.0") { exit 1 }' >/dev/null
}

validate_wheel() {
  [[ -s "$WHEEL" ]] || return 1
  if find pipeline/playtest_pipeline pipeline/pyproject.toml pipeline/setup.py pipeline/ffmpeg-release.json pipeline/tools/build_release_wheel.py packages/player-embed/report-template.html -type f -newer "$WHEEL" -print -quit 2>/dev/null | grep -q .; then return 1; fi
  M5_WHEEL_PATH="$(to_win "$WHEEL")" M5_TEMPLATE_PATH="$(to_win "$REPO_DIR/packages/player-embed/report-template.html")" powershell.exe -NoProfile -Command 'Add-Type -AssemblyName System.IO.Compression.FileSystem; $zip=[IO.Compression.ZipFile]::OpenRead($env:M5_WHEEL_PATH); try { $required=@("playtest_pipeline/bin/ffmpeg.exe","playtest_pipeline/bin/ffprobe.exe","playtest_pipeline/bin/LICENSE.txt","playtest_pipeline/report-template.html"); $entries=@{}; foreach($entry in $zip.Entries){$entries[$entry.FullName]=$entry}; foreach($name in $required){if(-not $entries.ContainsKey($name)){exit 1}; $stream=$entries[$name].Open(); try{$buffer=New-Object byte[] 65536; while($stream.Read($buffer,0,$buffer.Length)-gt 0){}} finally{$stream.Dispose()}}; $wheelEntry=$zip.Entries | Where-Object FullName -like "*.dist-info/WHEEL" | Select-Object -First 1; if(-not $wheelEntry){exit 1}; $reader=[IO.StreamReader]::new($wheelEntry.Open()); try{$metadata=$reader.ReadToEnd()} finally{$reader.Dispose()}; if($metadata -notmatch "Tag: py3-none-win_amd64"){exit 1}; $licenseReader=[IO.StreamReader]::new($entries["playtest_pipeline/bin/LICENSE.txt"].Open()); try{$license=$licenseReader.ReadToEnd()} finally{$licenseReader.Dispose()}; if($license -notmatch "GNU LESSER GENERAL PUBLIC LICENSE"){exit 1}; $templateStream=$entries["playtest_pipeline/report-template.html"].Open(); $memory=[IO.MemoryStream]::new(); $sha=[Security.Cryptography.SHA256]::Create(); try{$templateStream.CopyTo($memory); $wheelHash=([BitConverter]::ToString($sha.ComputeHash($memory.ToArray()))).Replace("-",""); $sourceHash=(Get-FileHash -LiteralPath $env:M5_TEMPLATE_PATH -Algorithm SHA256).Hash; if($wheelHash -ne $sourceHash){exit 1}} finally{$sha.Dispose();$templateStream.Dispose();$memory.Dispose()} } finally {$zip.Dispose()}' >/dev/null
}

capture_helper_current() {
  [[ -s "$CAPTURE_HELPER" ]] || return 1
  ! find helper/capture-helper/src helper/capture-helper/Cargo.toml helper/capture-helper/Cargo.lock -type f -newer "$CAPTURE_HELPER" -print -quit 2>/dev/null | grep -q .
}

prepare_installer() {
  if ! capture_helper_current; then
    warn "capture-helper.exe is missing or stale relative to its Rust inputs. Rebuilding that installer input now."
    require_cmd cargo "Install Rust from https://rustup.rs; the installer release input capture-helper.exe must be built."
    until capture_helper_current; do run_step "build capture-helper.exe" cargo build --release --manifest-path helper/capture-helper/Cargo.toml; done
  fi
  if validate_installer; then say "${GREEN}✓${RESET} verified current, non-stale recorder installer and bundled capture-helper input."; return; fi
  warn "The recorder installer is missing, invalid, or older than its release inputs. Rebuilding it now; no Sandbox action is needed."
  require_cmd npm "Install Node.js 20+ from https://nodejs.org; npm builds the recorder installer."
  require_file "$REPO_DIR/node_modules/electron/package.json" "install repository Node dependencies" npm install
  until validate_installer; do
    run_step "build the recorder NSIS installer" npm run dist -w playtest-recorder
    validate_installer || warn "The build returned but the expected versioned installer or capture-helper check still does not pass; retry the build."
  done
}

prepare_wheel() {
  if validate_wheel; then say "${GREEN}✓${RESET} verified the current Windows wheel, bundled FFmpeg/ffprobe entries, LGPL notice, platform tag, template, and source freshness."; return; fi
  warn "The selected wheel is missing, invalid, or stale. Rebuilding it with pipeline/tools/build_release_wheel.py; no external FFmpeg install is used."
  require_host_python
  until validate_wheel; do
    run_step "build and verify the selected bundled-FFmpeg release wheel" "${PYTHON_CMD[@]}" pipeline/tools/build_release_wheel.py
    validate_wheel || warn "The current release builder returned but the selected wheel still does not validate; retry the builder."
  done
}

new_run_id() {
  local candidate; candidate="$(date -u +%Y%m%dT%H%M%SZ)"
  while [[ -e "$TRANSFER_BASE/$candidate" ]]; do candidate="${candidate}-retry"; done
  printf '%s' "$candidate"
}

manifest_matches_run() {
  local manifest="$1" run_id="$2" installer_hash="$3" wheel_hash="$4" helper_hash="$5" wizard_helper_hash="$6" ffmpeg_hash="$7" ffprobe_hash="$8"
  M5_MANIFEST="$(to_win "$manifest")" M5_RUN_ID="$run_id" M5_INSTALLER_HASH="$installer_hash" M5_WHEEL_HASH="$wheel_hash" M5_HELPER_HASH="$helper_hash" M5_WIZARD_HELPER_HASH="$wizard_helper_hash" M5_FFMPEG_HASH="$ffmpeg_hash" M5_FFPROBE_HASH="$ffprobe_hash" powershell.exe -NoProfile -Command 'try{$m=Get-Content -LiteralPath $env:M5_MANIFEST -Raw|ConvertFrom-Json;if($m.schema -ne "m5-sandbox-kit-v2" -or $m.runId -ne $env:M5_RUN_ID -or $m.installer.sha256 -ne $env:M5_INSTALLER_HASH -or $m.wheel.sha256 -ne $env:M5_WHEEL_HASH -or $m.captureHelper.sha256 -ne $env:M5_HELPER_HASH -or $m.sandboxHelper.sha256 -ne $env:M5_WIZARD_HELPER_HASH -or $m.wheel.bundledFfmpegSha256 -ne $env:M5_FFMPEG_HASH -or $m.wheel.bundledFfprobeSha256 -ne $env:M5_FFPROBE_HASH){exit 1}}catch{exit 1}' >/dev/null
}

choose_run() {
  local installer_hash="$1" wheel_hash="$2" helper_hash="$3" wizard_helper_hash="$4" ffmpeg_hash="$5" ffprobe_hash="$6" candidate="" manifest=""
  mkdir -p "$TRANSFER_BASE"
  [[ -f "$CURRENT_RUN_FILE" ]] && candidate="$(tr -d '\r\n' < "$CURRENT_RUN_FILE")"
  manifest="$TRANSFER_BASE/$candidate/kit/kit-manifest.json"
  if [[ -n "$candidate" && -f "$manifest" ]] && ! compgen -G "$REPO_DIR/verification/evidence/m5/${candidate}-windows-sandbox*.md" >/dev/null && manifest_matches_run "$manifest" "$candidate" "$installer_hash" "$wheel_hash" "$helper_hash" "$wizard_helper_hash" "$ffmpeg_hash" "$ffprobe_hash"; then
    RUN_ID="$candidate"
    say "Resuming current incomplete run $RUN_ID; only host-accepted evidence for this identity can be reused."
  else
    RUN_ID="$(new_run_id)"
    printf '%s\n' "$RUN_ID" > "$CURRENT_RUN_FILE"
    say "Starting mapped run $RUN_ID. Prior runs, answers, and evidence are not overwritten or accepted."
  fi
  RUN_ROOT="$TRANSFER_BASE/$RUN_ID"
  KIT="$RUN_ROOT/kit"
  OUTBOX="$RUN_ROOT/outbox"
  HOST_EVIDENCE="$RUN_ROOT/host-evidence"
  STATE_FILE="$RUN_ROOT/wizard-state.env"
  WSB="$RUN_ROOT/Launch-M5-Windows-Sandbox.wsb"
  mkdir -p "$KIT" "$OUTBOX" "$HOST_EVIDENCE"
  ENV_FILE="$STATE_FILE"
}

write_lines() {
  local path="$1"; shift
  printf '%s\n' "$@" > "$path"
}

copy_verified() {
  local source="$1" destination="$2" expected_hash="$3" partial="${destination}.part"
  if [[ -f "$destination" && "$(sha256_file "$destination")" == "$expected_hash" ]]; then return; fi
  rm -f "$partial"
  cp "$source" "$partial"
  if [[ "$(sha256_file "$partial")" != "$expected_hash" ]]; then rm -f "$partial"; warn "The copy to $(to_win "$destination") did not match its source SHA-256; retrying."; return 1; fi
  mv -f "$partial" "$destination"
}

prepare_transfer_kit() {
  local installer_hash="$1" wheel_hash="$2" helper_hash="$3" wizard_helper_hash="$4" ffmpeg_hash="$5" ffprobe_hash="$6"
  until copy_verified "$INSTALLER" "$KIT/Playtest Recorder Setup 0.1.0.exe" "$installer_hash"; do pause "Press Enter to retry the verified installer copy."; done
  until copy_verified "$WHEEL" "$KIT/playtest_pipeline-0.1.0-py3-none-win_amd64.whl" "$wheel_hash"; do pause "Press Enter to retry the verified wheel copy."; done
  until copy_verified "$SANDBOX_HELPER_SOURCE" "$KIT/m5-sandbox-checks.ps1" "$wizard_helper_hash"; do pause "Press Enter to retry the verified Sandbox helper copy."; done
  M5_STAGED_INSTALLER="$(to_win "$KIT/Playtest Recorder Setup 0.1.0.exe")" powershell.exe -NoProfile -Command 'Set-Content -LiteralPath $env:M5_STAGED_INSTALLER -Stream Zone.Identifier -Value "[ZoneTransfer]`r`nZoneId=3`r`n" -Encoding ascii; $zone=Get-Content -LiteralPath $env:M5_STAGED_INSTALLER -Stream Zone.Identifier -Raw; if($zone -notmatch "(?m)^ZoneId=3\\r?$"){exit 1}'
  [[ "$(sha256_file "$KIT/Playtest Recorder Setup 0.1.0.exe")" == "$installer_hash" ]] || { warn "Adding Mark-of-the-Web changed installer bytes unexpectedly; refusing the kit."; return 1; }
  write_lines "$KIT/OBS Studio 32.url" '[InternetShortcut]' 'URL=https://obsproject.com/download'
  write_lines "$KIT/Python 3.11+.url" '[InternetShortcut]' 'URL=https://www.python.org/downloads/windows/'
  write_lines "$KIT/00-confirm-run.cmd" '@echo off' 'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "C:\M5Kit\m5-sandbox-checks.ps1" -Action ConfirmRun -KitDirectory "C:\M5Kit" -OutboxDirectory "C:\M5Outbox"' 'pause'
  write_lines "$KIT/01-installed-check.cmd" '@echo off' 'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "C:\M5Kit\m5-sandbox-checks.ps1" -Action Installed -KitDirectory "C:\M5Kit" -OutboxDirectory "C:\M5Outbox"' 'pause'
  write_lines "$KIT/02-install-negative-fixture.cmd" '@echo off' 'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "C:\M5Kit\m5-sandbox-checks.ps1" -Action InstallFixture -KitDirectory "C:\M5Kit" -OutboxDirectory "C:\M5Outbox"' 'pause'
  write_lines "$KIT/03-pipeline-tools-check.cmd" '@echo off' 'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "C:\M5Kit\m5-sandbox-checks.ps1" -Action PipelineTools -KitDirectory "C:\M5Kit" -OutboxDirectory "C:\M5Outbox"' 'pause'
  write_lines "$KIT/04-collect-live-evidence.cmd" '@echo off' 'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "C:\M5Kit\m5-sandbox-checks.ps1" -Action Collect -KitDirectory "C:\M5Kit" -OutboxDirectory "C:\M5Outbox"' 'pause'
  M5_MANIFEST="$(to_win "$KIT/kit-manifest.json")" M5_INSTALLER="$(to_win "$KIT/Playtest Recorder Setup 0.1.0.exe")" M5_WHEEL="$(to_win "$KIT/playtest_pipeline-0.1.0-py3-none-win_amd64.whl")" M5_RUN_ID="$RUN_ID" M5_INSTALLER_HASH="$installer_hash" M5_WHEEL_HASH="$wheel_hash" M5_HELPER_HASH="$helper_hash" M5_WIZARD_HELPER_HASH="$wizard_helper_hash" M5_FFMPEG_HASH="$ffmpeg_hash" M5_FFPROBE_HASH="$ffprobe_hash" powershell.exe -NoProfile -Command '$installer=Get-Item -LiteralPath $env:M5_INSTALLER;$wheel=Get-Item -LiteralPath $env:M5_WHEEL;$signature=Get-AuthenticodeSignature -LiteralPath $env:M5_INSTALLER;$createdAt=(Get-Date).ToUniversalTime().ToString("o");if(Test-Path -LiteralPath $env:M5_MANIFEST){try{$old=Get-Content -LiteralPath $env:M5_MANIFEST -Raw|ConvertFrom-Json;if($old.schema -eq "m5-sandbox-kit-v2" -and $old.runId -eq $env:M5_RUN_ID -and $old.createdAtUtc){$createdAt=[string]$old.createdAtUtc}}catch{}};$manifest=[ordered]@{schema="m5-sandbox-kit-v2";runId=$env:M5_RUN_ID;createdAtUtc=$createdAt;installer=[ordered]@{name=$installer.Name;version=$installer.VersionInfo.ProductVersion;bytes=$installer.Length;sha256=$env:M5_INSTALLER_HASH;signatureStatus=[string]$signature.Status;motwZoneId=3};wheel=[ordered]@{name=$wheel.Name;bytes=$wheel.Length;sha256=$env:M5_WHEEL_HASH;bundledFfmpegSha256=$env:M5_FFMPEG_HASH;bundledFfprobeSha256=$env:M5_FFPROBE_HASH};captureHelper=[ordered]@{sha256=$env:M5_HELPER_HASH};sandboxHelper=[ordered]@{name="m5-sandbox-checks.ps1";sha256=$env:M5_WIZARD_HELPER_HASH};ffmpegBoundary="Selected wheel-bundled ffmpeg/ffprobe, invoked as separate processes; no external FFmpeg install."};$tmp="$env:M5_MANIFEST.part";$manifest|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $tmp -Encoding utf8;Move-Item -LiteralPath $tmp -Destination $env:M5_MANIFEST -Force'
  M5_KIT="$(to_win "$KIT")" M5_OUTBOX="$(to_win "$OUTBOX")" M5_WSB="$(to_win "$WSB")" powershell.exe -NoProfile -Command '$kit=[Security.SecurityElement]::Escape($env:M5_KIT);$outbox=[Security.SecurityElement]::Escape($env:M5_OUTBOX);$xml="<Configuration>`r`n  <MappedFolders>`r`n    <MappedFolder>`r`n      <HostFolder>$kit</HostFolder>`r`n      <SandboxFolder>C:\M5Kit</SandboxFolder>`r`n      <ReadOnly>true</ReadOnly>`r`n    </MappedFolder>`r`n    <MappedFolder>`r`n      <HostFolder>$outbox</HostFolder>`r`n      <SandboxFolder>C:\M5Outbox</SandboxFolder>`r`n      <ReadOnly>false</ReadOnly>`r`n    </MappedFolder>`r`n  </MappedFolders>`r`n  <Networking>Enable</Networking>`r`n  <AudioInput>Enable</AudioInput>`r`n  <ClipboardRedirection>Enable</ClipboardRedirection>`r`n</Configuration>`r`n";[IO.File]::WriteAllText($env:M5_WSB,$xml,[Text.UTF8Encoding]::new($false))'
  MANIFEST_HASH="$(sha256_file "$KIT/kit-manifest.json")"
}

sandbox_state() {
  powershell.exe -NoProfile -Command 'if(Test-Path -LiteralPath "$env:WINDIR\System32\WindowsSandbox.exe"){"Enabled"}elseif(Test-Path -LiteralPath "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending"){"EnableOrRebootPending"}else{"Disabled"}' 2>/dev/null | tr -d '\r'
}

sandbox_edition_supported() {
  powershell.exe -NoProfile -Command '$edition=(Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion").EditionID; if($edition -match "^(Professional|ProfessionalN|ProfessionalEducation|ProfessionalEducationN|ProfessionalWorkstation|ProfessionalWorkstationN|Enterprise|EnterpriseN|EnterpriseS|EnterpriseSN|Education|EducationN)$"){exit 0}else{Write-Output $edition;exit 1}'
}

virtualization_ready() {
  powershell.exe -NoProfile -Command '$cpu=Get-CimInstance Win32_Processor -ErrorAction SilentlyContinue | Select-Object -First 1; $computer=Get-CimInstance Win32_ComputerSystem -ErrorAction SilentlyContinue; if($computer.HypervisorPresent -or $cpu.VirtualizationFirmwareEnabled){exit 0}else{exit 1}' >/dev/null 2>&1
}

sandbox_running() {
  powershell.exe -NoProfile -Command 'if(Get-Process -Name "WindowsSandbox*" -ErrorAction SilentlyContinue){exit 0}else{exit 1}' >/dev/null 2>&1
}

ensure_sandbox_available() {
  local state edition
  until sandbox_edition_supported >/dev/null 2>&1; do
    edition="$(powershell.exe -NoProfile -Command '(Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion").EditionID' | tr -d '\r')"
    warn "Windows edition '$edition' does not expose Windows Sandbox. Use a supported Windows Pro, Enterprise, or Education host; do not use third-party feature hacks."
    pause "After moving this repository/run to a supported host, press Enter to detect the edition again. Ctrl-C preserves the prepared run for resume."
  done
  until virtualization_ready; do
    warn "Windows reports neither an active hypervisor nor firmware virtualization. Open Task Manager → Performance → CPU and check Virtualization; if disabled, enable Intel VT-x/AMD-V in UEFI firmware and reboot."
    say "After reboot, return to the repository and run: $RUN_COMMAND. The prepared artifacts and answers resume without replacement."
    pause "Virtualization enabled and any required reboot complete? Press Enter to detect it again."
  done
  while :; do
    state="$(sandbox_state)"
    [[ "$state" == "Enabled" ]] && break
    warn "Windows Sandbox feature state: $state."
    say "Open the exact Windows Features dialog with Win+R → optionalfeatures.exe, check Windows Sandbox, click OK, and let Windows apply it."
    say "The wizard is opening Windows Features now; this loop continues until WindowsSandbox.exe confirms the feature is installed."
    powershell.exe -NoProfile -Command 'Start-Process optionalfeatures.exe' >/dev/null 2>&1 || true
    warn "If Windows requests a restart, leave this run directory intact, reboot Windows, return to the repository, and run: $RUN_COMMAND"
    say "The wizard will resume the same run without rebuilding or replacing valid answers. A requested reboot naturally stops this shell; it is a recoverable feature-enable step, not a failed release run."
    pause "After Windows Sandbox is enabled (and after reboot if Windows requests it), press Enter to check the feature again."
  done
  say "${GREEN}✓${RESET} supported Windows edition, virtualization, and the Windows Sandbox feature are available."
}

launch_or_resume_sandbox() {
  local identity_marker="$RUN_ROOT/guest-identity-attempt.marker"
  while :; do
    if ! sandbox_running; then
      say "Launching the generated configuration: $(to_win "$WSB")"
      M5_WSB_PATH="$(to_win "$WSB")" powershell.exe -NoProfile -Command 'Start-Process -FilePath "$env:WINDIR\System32\WindowsSandbox.exe" -ArgumentList ("`"{0}`"" -f $env:M5_WSB_PATH)' >/dev/null
      until sandbox_running; do
        warn "Windows Sandbox has not appeared yet. Wait for initialization; if Windows shows an error, correct it and retry the launcher."
        if confirm "Retry opening the generated .wsb launcher now?"; then M5_WSB_PATH="$(to_win "$WSB")" powershell.exe -NoProfile -Command 'Start-Process -FilePath "$env:WINDIR\System32\WindowsSandbox.exe" -ArgumentList ("`"{0}`"" -f $env:M5_WSB_PATH)' >/dev/null; else pause "Keep waiting, then press Enter to check again."; fi
      done
    else
      say "An existing Windows Sandbox is running; its mapping must prove it belongs to selected run $RUN_ID before resume."
    fi
    touch "$identity_marker"
    step "Inside the running Sandbox, open C:\\M5Kit and double-click 00-confirm-run.cmd. The read-only helper proves the run ID, manifest, installer/wheel/helper hashes, bundled-tool hashes, and installer ZoneId=3 before any launch."
    pause "The confirmation window reports pass? Press Enter so the trusted tracked host helper can verify a fresh identity result for run $RUN_ID."
    if validate_guest_evidence guest-confirm "$identity_marker"; then say "${GREEN}✓${RESET} Sandbox read-only kit and dedicated outbox are bound to selected run $RUN_ID."; return; fi
    warn "No fresh passing identity for run $RUN_ID reached this outbox. The Sandbox may use an older mapping or its kit may be damaged."
    if confirm "Retry 00-confirm-run.cmd in this same Sandbox?"; then continue; fi
    warn "Before closing this Sandbox, copy any evidence you need; closing permanently discards guest-only files."
    pause "After copying anything needed and closing the mismatched Sandbox, press Enter to relaunch the selected .wsb."
    while sandbox_running; do pause "Sandbox is still running. Close it only after copying needed evidence, then press Enter to check again."; done
  done
}

record_check() {
  local key="$1" question="$2" retry_instruction="$3" current="" reply=""
  current="$(_existing "$key" || true)"
  if [[ "$current" == "yes" ]]; then say "${GREEN}✓${RESET} resuming saved PASS observation: $question"; return; fi
  [[ "$current" == "no" ]] && warn "A prior attempt recorded this criterion as failed; re-check it now if you corrected the issue."
  while :; do
    if confirm "$question"; then write_env "$key" yes; return; fi
    warn "$retry_instruction"
    printf '  %s? [r]etry the observation / record [f]ailure / [a]bort and resume later%s ' "$YELLOW" "$RESET"
    read -r reply || true
    case "$reply" in
      f|F) write_env "$key" no; return ;;
      a|A) printf '  aborted — keep Sandbox open if possible and re-run %s to resume.\n' "$RUN_COMMAND"; exit 1 ;;
      *) pause "Perform the corrective action now, then press Enter to observe the criterion again." ;;
    esac
  done
}

host_helper() {
  local action="$1"; shift
  powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$(to_win "$SANDBOX_HELPER_SOURCE")" -Action "$action" -KitDirectory "$(to_win "$KIT")" -OutboxDirectory "$(to_win "$OUTBOX")" -HostEvidenceDirectory "$(to_win "$HOST_EVIDENCE")" -ExpectedRunId "$RUN_ID" -ExpectedManifestSha256 "$MANIFEST_HASH" -ExpectedHostHelperSha256 "$SANDBOX_HELPER_HASH" "$@"
}

validate_guest_evidence() {
  local kind="$1" marker="${2:-}" args=(-EvidenceKind "$kind")
  [[ -n "$marker" ]] && args+=(-AttemptMarkerPath "$(to_win "$marker")")
  host_helper ValidateGuestEvidence "${args[@]}"
}

require_screenshot() {
  local kind="$1" view="$2" result_key="$3" reply="" marker="$RUN_ROOT/screenshot-$kind-attempt.marker" exact_name="$RUN_ID-$kind.png"
  if host_helper ValidateScreenshot -ScreenshotKind "$kind" >/dev/null 2>&1; then say "${GREEN}✓${RESET} reusing host-decoded, hash-bound current-run PNG for $kind."; write_env "$result_key" yes; return; fi
  while :; do
    rm -f "$marker"; touch "$marker"
    step "Leave $view visible. Capture the relevant app/dialog area as a real PNG and save exactly as C:\\M5Outbox\\$exact_name. If a guest modal blocks Snipping Tool, use the host's Win+Shift+S and save to $(to_win "$OUTBOX/$exact_name")."
    note "Do not capture passwords, tokens, browser profiles, or any other secret. This release run needs no credentials."
    pause "Current-attempt screenshot saved? Press Enter for trusted host PNG decode, run-identity, freshness, and hash validation."
    if host_helper ValidateScreenshot -ScreenshotKind "$kind" -AttemptMarkerPath "$(to_win "$marker")"; then
      if confirm "Open the saved PNG if needed: does it visibly and legibly show $view, rather than a blank, unrelated, or duplicate view?"; then
        if host_helper ConfirmScreenshotVisual -ScreenshotKind "$kind"; then write_env "$result_key" yes; return; fi
        warn "The trusted helper could not bind the human visual confirmation to the accepted PNG; retry this gate."
      fi
      rm -f "$HOST_EVIDENCE/accepted-screenshot-$kind.json" "$HOST_EVIDENCE/visual-confirmed-screenshot-$kind.json"
      warn "Visual-content confirmation failed or could not be bound, so host acceptance was removed; capture the named criterion again."
    fi
    warn "The screenshot gate rejected missing, stale, misnamed, undersized, non-PNG, undecodable, changed, wrong-run, unrelated, or duplicate evidence."
    printf '  %s? [r]etry screenshot / record [f]ailed evidence / [a]bort and resume later%s ' "$YELLOW" "$RESET"
    read -r reply || true
    case "$reply" in
      f|F) write_env "$result_key" no; return ;;
      a|A) printf '  aborted — keep Sandbox open and re-run %s to resume.\n' "$RUN_COMMAND"; exit 1 ;;
    esac
  done
}

require_passing_json() {
  local kind="$1" command_file="$2" purpose="$3" result_key="$4" reply="" marker="$RUN_ROOT/$kind-attempt.marker"
  if validate_guest_evidence "$kind" >/dev/null 2>&1; then say "${GREEN}✓${RESET} reusing trusted-host-accepted current-run $purpose evidence."; write_env "$result_key" yes; return; fi
  while :; do
    rm -f "$marker"; touch "$marker"
    step "In Windows Sandbox, open the read-only C:\\M5Kit and double-click $command_file. It may write JSON only to C:\\M5Outbox; read the visible output."
    pause "The guest helper reports pass? Press Enter for strict validation by the tracked host-only helper."
    if validate_guest_evidence "$kind" "$marker"; then write_env "$result_key" yes; return; fi
    warn "No fresh $purpose JSON passed schema, run/attempt, manifest/artifact identity, exact-check-set, timestamp, and host acceptance validation."
    printf '  %s? [r]etry helper / record [f]ailed evidence / [a]bort and resume later%s ' "$YELLOW" "$RESET"
    read -r reply || true
    case "$reply" in
      f|F) write_env "$result_key" no; return ;;
      a|A) printf '  aborted — keep Sandbox open and re-run %s to resume.\n' "$RUN_COMMAND"; exit 1 ;;
    esac
  done
}

ask_limitations() {
  local current
  current="$(_existing LIMITATIONS || true)"
  if [[ -n "$current" ]]; then say "Saved limitations/failures: $current"; confirm "Keep this saved limitations/failures text?" && return; fi
  say "Describe any Sandbox, hardware, transcription, OBS, or report limitation. Enter 'none' only if there was none. Never paste a password or token."
  until [[ -n "${LIMITATIONS:-}" ]]; do ask LIMITATIONS "Limitations/failures (or none):"; [[ -n "$LIMITATIONS" ]] || warn "Enter 'none' or a concise non-secret description; the outcome must not leave this field ambiguous."; done
  write_env LIMITATIONS "$LIMITATIONS"
}

state_answer() {
  _existing "$1" 2>/dev/null || printf 'missing'
}

write_outcome() {
  local status="$1" outcome="$REPO_DIR/verification/evidence/m5/${RUN_ID}-windows-sandbox.md" suffix=1 limitations escaped
  while [[ -e "$outcome" ]]; do outcome="$REPO_DIR/verification/evidence/m5/${RUN_ID}-windows-sandbox-retry-${suffix}.md"; suffix=$((suffix + 1)); done
  limitations="$(state_answer LIMITATIONS)"; escaped="${limitations//|/\\|}"
  cat > "$outcome" <<EOF
# M5 Windows Sandbox release exit — $RUN_ID

Status: **$status**

- Run UTC identity: $RUN_ID
- Recorded at UTC: $(date -u +%Y-%m-%dT%H:%M:%SZ)
- Machine: Windows Sandbox
- Host mapped run: verification/evidence/m5/.sandbox-transfer/$RUN_ID
- Installer: Playtest Recorder Setup 0.1.0.exe
- Installer SHA-256: $INSTALLER_HASH
- Installer signature status at kit preparation: $INSTALLER_SIGNATURE
- Wheel: playtest_pipeline-0.1.0-py3-none-win_amd64.whl
- Wheel SHA-256: $WHEEL_HASH
- Capture helper SHA-256 expected by installed check: $CAPTURE_HELPER_HASH
- FFmpeg boundary: FFmpeg and ffprobe came from the selected wheel and were checked with PATH sanitized; OBS remained a separately installed application driven through obs-websocket.

## Observations

| Release-exit criterion | Result |
| --- | --- |
| SmartScreen reputation UI showed Windows protected your PC → More info → Run anyway | $(state_answer SMARTSCREEN_REPUTATION_OK) |
| Installer offered install-directory choice for the assisted per-user install | $(state_answer INSTALL_DIR_OK) |
| Start-menu shortcut and installed recorder verified | $(state_answer START_SHORTCUT_OK) |
| Fresh first-run wizard opened | $(state_answer FIRST_RUN_OK) |
| Detect OBS reported not found before OBS install | $(state_answer OBS_NOT_FOUND_OK) |
| Installed resources\\capture-helper.exe automated check passed | $(state_answer INSTALLED_HELPER_OK) |
| HID/controller binding or no-missing-helper log fallback observed | $(state_answer HID_FALLBACK_OK) |
| Before Python install, app log clearly showed playtest-pipeline command not recognized | $(state_answer MISSING_COMMAND_OK) |
| Expected negative run exited with code 1 and was not treated as release completion | $(state_answer MISSING_EXIT_OK) |
| Official OBS Studio major version 32 installed | $(state_answer OBS32_OK) |
| Official Python 3.11+ installed and prepared wheel installed | $(state_answer PYTHON_WHEEL_OK) |
| Installed package resolved bundled FFmpeg and ffprobe without PATH | $(state_answer BUNDLED_TOOLS_OK) |
| Recorder setup wizard, OBS websocket, recording profile, and preflight were completed | $(state_answer OBS_SETUP_OK) |
| Routed microphone meter visibly moved before the dictated-note run | $(state_answer MICROPHONE_METER_OK) |
| Live session duration was at least 10 seconds | $(state_answer LIVE_DURATION_OK) |
| Human made at least one real mark and dictated a note during the live recording | $(state_answer LIVE_MARK_OK) |
| Pipeline ran from the installed app and emitted a report | $(state_answer LIVE_PIPELINE_OK) |
| Condensed video played in the emitted report | $(state_answer REPORT_PLAYABLE_OK) |
| Report showed data for the real note/mark | $(state_answer REPORT_NOTE_OK) |
| Real note contained recognizable nonempty dictated-note transcription | $(state_answer REPORT_TRANSCRIPT_OK) |
| Report seeking landed on the marked content | $(state_answer REPORT_SEEK_OK) |
| Original-to-condensed time mapping was coherent by human observation | $(state_answer REPORT_MAPPING_OK) |
| SmartScreen, first-run, helper, missing-pipeline, preflight, live-pipeline, and live-report PNGs decoded and hash-bound | $(state_answer SMARTSCREEN_SCREENSHOT_OK), $(state_answer FIRST_RUN_SCREENSHOT_OK), $(state_answer HELPER_SCREENSHOT_OK), $(state_answer MISSING_PIPELINE_SCREENSHOT_OK), $(state_answer OBS_PREFLIGHT_SCREENSHOT_OK), $(state_answer LIVE_PIPELINE_SCREENSHOT_OK), $(state_answer LIVE_REPORT_SCREENSHOT_OK) |
| Installed, pipeline-tools, and collection automated JSON gates passed | $(state_answer INSTALLED_JSON_OK), $(state_answer PIPELINE_TOOLS_JSON_OK), $(state_answer COLLECTION_JSON_OK) |
| Required screenshots, automated JSON, live session, recording, and report copied before Sandbox close | $(state_answer COPIED_EVIDENCE_OK) |

## Limitations and failures

$escaped

## Evidence inventory

- Read-only kit/kit-manifest.json binds the run, installer/wheel/helper identities, bundled-tool hashes, and installer ZoneId=3.
- Guest-writable outbox JSON uses the m5-sandbox-evidence-v2 schema with runId, unique attemptId, manifest hash, complete artifact identities, and an exact required check set.
- Host-only host-evidence/ records bind each accepted guest JSON, decoded PNG, and separate human visual confirmation by SHA-256; host validation is produced there, never in the guest-writable outbox.
- outbox/sessions/ contains the copied live session, source recording, emitted report, and pipeline artifacts bound by session/report IDs, mark-note correspondence, hashes, and trusted bundled-ffprobe probes.

Synthetic fixture note: m5-missing-pipeline-fixture was used only to trigger the expected command-resolution failure before Python installation. It is not the live release evidence and did not contribute to PASS.
EOF
  printf '%s' "$outcome"
}

banner "M5 — clean-machine Windows Sandbox release exit"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Host prep: release artifacts, mapped evidence kit, and Sandbox"
say "The host performs every automatable preparation step. The human work begins only after Windows Sandbox opens."
say "No external FFmpeg is installed: the current release-wheel builder owns the pinned bundled FFmpeg/ffprobe payload. OBS remains a separate official install."
prepare_installer
prepare_wheel
INSTALLER_HASH="$(sha256_file "$INSTALLER")"
WHEEL_HASH="$(sha256_file "$WHEEL")"
CAPTURE_HELPER_HASH="$(sha256_file "$CAPTURE_HELPER")"
SANDBOX_HELPER_HASH="$(sha256_file "$SANDBOX_HELPER_SOURCE")"
WHEEL_FFMPEG_HASH="$(wheel_entry_sha256 'playtest_pipeline/bin/ffmpeg.exe')"
WHEEL_FFPROBE_HASH="$(wheel_entry_sha256 'playtest_pipeline/bin/ffprobe.exe')"
choose_run "$INSTALLER_HASH" "$WHEEL_HASH" "$CAPTURE_HELPER_HASH" "$SANDBOX_HELPER_HASH" "$WHEEL_FFMPEG_HASH" "$WHEEL_FFPROBE_HASH"
prepare_transfer_kit "$INSTALLER_HASH" "$WHEEL_HASH" "$CAPTURE_HELPER_HASH" "$SANDBOX_HELPER_HASH" "$WHEEL_FFMPEG_HASH" "$WHEEL_FFPROBE_HASH"
INSTALLER_SIGNATURE="$(M5_INSTALLER_PATH="$(to_win "$INSTALLER")" powershell.exe -NoProfile -Command '(Get-AuthenticodeSignature -LiteralPath $env:M5_INSTALLER_PATH).Status' | tr -d '\r')"
say "Installer SHA-256: $INSTALLER_HASH"
say "Wheel SHA-256: $WHEEL_HASH"
say "Read-only kit mapping: $(to_win "$KIT") → C:\\M5Kit"
say "Only guest-writable mapping: $(to_win "$OUTBOX") → C:\\M5Outbox"
say "Host-only state, current-run pointer, .wsb, markers, acceptances, and validation stay outside both mapped folders."
ensure_sandbox_available
launch_or_resume_sandbox
pause "Windows Sandbox is ready with C:\\M5Kit read-only and C:\\M5Outbox writable? Press Enter for the bare-machine installer check (stage 2)."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Bare machine: install recorder, first run, helper, and HID fallback"
say "Work only inside Windows Sandbox. Do not close it until stage 6 says the mapped evidence is validated. Closing Sandbox permanently discards anything not copied to C:\\M5Outbox."
say "00-confirm-run already proved that the read-only installer is hash-identical to the host release artifact and carries Mark-of-the-Web ZoneId=3. The required unsigned-installer gate is SmartScreen reputation, not elevation."
step "Inside Sandbox, open File Explorer → C:\\M5Kit → double-click Playtest Recorder Setup 0.1.0.exe. Verify the SmartScreen dialog says Windows protected your PC, choose More info, and do not choose Run anyway yet."
record_check SMARTSCREEN_REPUTATION_OK "Did Windows SmartScreen specifically show 'Windows protected your PC', and did More info expose Run anyway?" "Retry the ZoneId=3 installer from C:\\M5Kit. If this exact SmartScreen sequence still does not show, record failure. A UAC prompt, if Windows shows one, cannot satisfy this reputation gate."
require_screenshot 'smartscreen-reputation' "the expanded Windows SmartScreen 'Windows protected your PC' reputation dialog with Run anyway visible" SMARTSCREEN_SCREENSHOT_OK
step "On the expanded SmartScreen reputation dialog choose Run anyway to enter the assisted installer. This explicit Windows protected your PC → More info → Run anyway sequence is the required SmartScreen observation."
note "The installer runs asInvoker and defaults to a current-user install, so the normal path does not show UAC. If an install-mode page offers All Users, keep the current-user/Only for me choice; do not select All Users merely to provoke elevation. If Windows nevertheless shows UAC, treat it as optional system behavior, not SmartScreen or required evidence, and continue only if you are comfortable approving it."
step "In the assisted installer, keep the intended current-user install, confirm the destination page offers a directory choice, keep the default per-user directory or deliberately choose another per-user directory and note it, continue Install, and leave Run Playtest Recorder selected."
record_check INSTALL_DIR_OK "Did the installer offer an install-directory choice and install into the selected directory?" "Run the installer again and verify the destination chooser; do not guess from the final path."
step "On first launch, confirm First-run setup opens. On the Detect OBS step choose Detect OBS before installing OBS; it must report not found."
record_check FIRST_RUN_OK "Did the fresh installed app automatically open its first-run setup wizard?" "Close the app, uninstall/reinstall within Sandbox if necessary, and launch from the Start menu to retry with fresh Sandbox state."
record_check OBS_NOT_FOUND_OK "Before OBS was installed, did Detect OBS clearly report OBS not found?" "Retry Detect OBS while the Sandbox is still bare. If OBS was already installed, this negative observation requires a fresh Sandbox rerun."
require_screenshot 'first-run-obs-not-found' "the recorder first-run wizard with the OBS-not-found result" FIRST_RUN_SCREENSHOT_OK
step "Leave the setup wizard with Skip setup for now so the Sessions card is usable; stage 4 reopens Setup wizard and completes it after OBS exists."
require_passing_json 'installed-check' '01-installed-check.cmd' 'installed recorder, Start-menu shortcut, and resources\\capture-helper.exe check' INSTALLED_JSON_OK
record_check START_SHORTCUT_OK "Did the automated installed check pass for the recorder and Start-menu shortcut?" "Reinstall or repair the selected destination, then rerun 01-installed-check.cmd."
record_check INSTALLED_HELPER_OK "Did the automated installed check find resources\\capture-helper.exe with the kit's expected SHA-256?" "Reinstall from the prepared installer and rerun 01-installed-check.cmd; do not substitute a manually copied helper."
step "In Hotkeys & options, click the Mark key button and press a connected controller/HID button. If no device is available, exercise the keyboard/log fallback and confirm the app log does not say capture-helper.exe not found."
record_check HID_FALLBACK_OK "Did a real controller/HID bind, or did the exercised fallback log avoid capture-helper.exe not found?" "Reconnect a device and retry binding, or exercise the fallback while watching the recorder log. Record failure if neither observation is available."
require_screenshot 'helper-hid' "the captured HID binding or the visible no-missing-helper log fallback" HELPER_SCREENSHOT_OK
pause "Bare-machine evidence is saved. Press Enter for the expected missing-pipeline negative check (stage 3); this negative result is not release completion."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Expected negative: pipeline command is missing before Python install"
say "This stage proves the packaged app fails clearly when its intentionally separate Python pipeline is absent. It cannot satisfy the release exit by itself."
step "Inside Sandbox, open read-only C:\\M5Kit and double-click 02-install-negative-fixture.cmd. It creates a valid Sessions-card fixture only for command resolution; collection explicitly rejects its ID."
pause "The helper says the negative-check fixture exists? Press Enter to continue in the installed recorder."
step "In Playtest Recorder, click Sessions → Refresh. On M5 expected missing-pipeline check only, click Run pipeline."
step "Read the app log. It must clearly include that playtest-pipeline is not recognized as a command, followed by Pipeline exited with code 1."
record_check MISSING_COMMAND_OK "Did the installed app log clearly report that playtest-pipeline was not recognized?" "Make sure Python and the pipeline have not yet been installed, refresh the fixture, rerun it from the Sessions card, and inspect the app log."
record_check MISSING_EXIT_OK "Did that same expected negative run end with Pipeline exited with code 1?" "Rerun the fixture from the Sessions card and keep the log visible through process exit. Do not accept the missing-command line without code 1."
require_screenshot 'missing-pipeline' "the recorder log showing both command-not-recognized and exit code 1" MISSING_PIPELINE_SCREENSHOT_OK
pause "Expected negative evidence is saved and explicitly not counted as completion. Press Enter to install release dependencies (stage 4)."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Release dependencies: official OBS 32, Python 3.11+, wheel, and preflight"
say "Use official browser downloads inside Sandbox. No account, credential, external FFmpeg download, purchase, or publishing action is needed."
step "Inside Sandbox File Explorer, double-click C:\\M5Kit\\OBS Studio 32.url. On the official OBS download page choose Windows and install OBS Studio major version 32. If the main button has moved to a newer major, use that official page's Previous Releases link and choose the newest official 32.x Windows installer; do not use a third-party download."
step "Double-click C:\\M5Kit\\Python 3.11+.url. On python.org choose the current Windows installer for Python 3.11 or newer, run it, select Add python.exe to PATH, and finish."
step "Open a new PowerShell inside Sandbox and run: py -3 --version"
step "In that same new PowerShell run: py -3 -m pip install \"C:\\M5Kit\\playtest_pipeline-0.1.0-py3-none-win_amd64.whl[all]\". The [all] metadata comes from the prepared wheel and installs its STT/VAD dependencies; FFmpeg and ffprobe still come only from that wheel."
step "Close Playtest Recorder completely, including its tray process, then launch it again from the Start menu so it inherits the newly installed pipeline command."
record_check OBS32_OK "Does OBS Help → About identify installed OBS Studio major version 32 from the official download?" "Return to the official OBS download page inside Sandbox and install the required major version; record failure if official version 32 cannot be installed."
record_check PYTHON_WHEEL_OK "Did py -3 report Python 3.11+ and did pip successfully install the prepared wheel with its [all] STT/VAD extras?" "Open a new PowerShell, correct the official Python PATH setup, rerun the exact wheel[all] install command, and observe success."
require_passing_json 'pipeline-tools-check' '03-pipeline-tools-check.cmd' 'pipeline CLI and selected-wheel-bundled FFmpeg/ffprobe without PATH' PIPELINE_TOOLS_JSON_OK
record_check BUNDLED_TOOLS_OK "Did 03-pipeline-tools-check.cmd pass with both tools resolving under playtest_pipeline\\bin while PATH was sanitized?" "Reinstall the prepared wheel, open a new PowerShell, and rerun the automated check. Do not install external FFmpeg or set PLAYTEST_FFMPEG_DIR."
step "Start OBS once. In the first-run Auto-Configuration Wizard choose Optimize just for recording, not streaming. Add a Display Capture source so the Sandbox desktop is recordable. The generated .wsb explicitly enables AudioInput, so microphone input is mandatory rather than optional."
step "OBS → Tools → WebSocket Server Settings → Enable WebSocket server. Do not copy or paste its password. Close OBS normally once so it saves its plugin config."
step "In Playtest Recorder click Setup wizard. Detect OBS, continue, start OBS when directed, connect, apply the recommended recording profile, restart OBS when directed, and continue through Face cam and Rig to Finish."
step "In OBS Advanced Audio Properties, keep desktop/game audio on track 1 and route the microphone to track 2. Speak continuously for several seconds while watching the OBS mixer; the microphone meter must visibly move before the live run is allowed."
record_check MICROPHONE_METER_OK "Did the routed microphone meter visibly move while you spoke, proving live audio input is present?" "Use OBS Settings → Audio to select the Sandbox microphone, verify host privacy/device access, and retry speaking. If no meter can move, record failure; do not claim or perform the mandatory dictated-note live run."
step "Back in the recorder, run preflight and correct actionable warnings; Sandbox hardware advisories may be recorded as limitations but must not be silently ignored."
record_check OBS_SETUP_OK "Did the recorder wizard complete with OBS websocket connection, recommended recording profile, and a reviewed preflight?" "Repeat the exact wizard/preflight path, restart OBS after applying settings, and correct or explicitly record every remaining warning."
require_screenshot 'obs-preflight' "the connected recorder with final preflight visible and the configured microphone mixer in context" OBS_PREFLIGHT_SCREENSHOT_OK
pause "Dependencies and OBS setup are captured. Press Enter for the required real recording and report observation (stage 5)."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Live exit run: real recording, mark/note, installed-app pipeline, and report"
say "This must be a real human-observed recording. The synthetic negative fixture cannot replace any step here. Keep Sandbox open through stage 6."
if [[ "$(state_answer MICROPHONE_METER_OK)" == yes ]]; then
step "In OBS, reconfirm Display Capture is visible and the required microphone meter moves. In Playtest Recorder enter a title beginning M5 Sandbox live, then Start recording."
step "Let it record for at least 10 seconds. Press the real Mark binding at least once and immediately dictate a short note; optionally press Issue and dictate another."
step "Use the Playtest Recorder tray icon to Stop. Reopen the recorder from the tray or Start menu and confirm the completed live session appears in Sessions."
record_check LIVE_DURATION_OK "Does the completed real session show a duration of at least 10 seconds?" "Record a new real session for longer than 10 seconds; do not edit timestamps or use the synthetic fixture."
record_check LIVE_MARK_OK "Did you make at least one real mark and dictate a note during that live recording?" "Record a new live session and use the actual configured mark input while recording, then speak immediately after it."
step "On that live session's Sessions card click Run pipeline. Keep the app open while the selected speech model downloads on first use and until the log reports exit code 0 and the session changes to Open report; no account or credential is required."
record_check LIVE_PIPELINE_OK "Did the pipeline run from the installed app, exit successfully, and emit Open report for the real session?" "Keep the recorder idle, rerun the pipeline from the live Sessions card, and correct any visible error."
require_screenshot 'live-pipeline' "the installed app's successful pipeline log and live session card" LIVE_PIPELINE_SCREENSHOT_OK
step "Click Open report. Play condensed.mp4 in the emitted report, locate the real note/mark row, click its timestamp, and compare the shown original time with the condensed playback position/content."
record_check REPORT_PLAYABLE_OK "Did the condensed video visibly play in the emitted report?" "Retry playback and the pipeline; record failure if the emitted condensed video is not playable."
record_check REPORT_NOTE_OK "Did the report show data corresponding to the real note/mark you made?" "Compare the live session's session.json marks with the report. Rerun the pipeline; do not use fixture data as a substitute."
record_check REPORT_TRANSCRIPT_OK "Did the real note row contain recognizable nonempty text transcribed from what you dictated?" "Confirm the wheel was installed with [all], the microphone was routed to track 2, speak clearly in a new live run, and rerun the pipeline; an empty mark label alone is not enough."
record_check REPORT_SEEK_OK "Did clicking the real note/mark timestamp seek to the marked content?" "Replay around the mark and retry the report link; record failure if seeking is wrong."
record_check REPORT_MAPPING_OK "Was the displayed original-to-condensed time mapping coherent with what you recorded and marked?" "Compare the report's original timestamp, condensed position, and visible recorded action; record failure rather than accepting an unexplained mismatch."
require_screenshot 'live-report' "the emitted report with playable video and the observed real note/mark/time mapping" LIVE_REPORT_SCREENSHOT_OK
step "Return to the live session card and use Folder to copy its full folder path. Inside Sandbox double-click C:\\M5Kit\\04-collect-live-evidence.cmd, paste that path when asked, and wait for copy plus hashes to finish."
step "The collector explicitly rejects m5-missing-pipeline-fixture; binds session.json to report_data.json by session ID/title/date and mark IDs/times; uses the selected wheel's bundled ffprobe for real source duration and condensed playability; and copies/hashes the source recording and report into C:\\M5Outbox."
require_passing_json 'collection' '04-collect-live-evidence.cmd' 'live session/report/source-media collection' COLLECTION_JSON_OK
else
  warn "The mandatory dictated-note run is blocked because no moving microphone meter was proven. Recording without live audio would create misleading evidence, so stage 5 is recorded as failed rather than allowed."
  for key in LIVE_DURATION_OK LIVE_MARK_OK LIVE_PIPELINE_OK REPORT_PLAYABLE_OK REPORT_NOTE_OK REPORT_TRANSCRIPT_OK REPORT_SEEK_OK REPORT_MAPPING_OK LIVE_PIPELINE_SCREENSHOT_OK LIVE_REPORT_SCREENSHOT_OK COLLECTION_JSON_OK; do write_env "$key" no; done
fi
say "Do not close Windows Sandbox. Stage 6 must validate the host-side mapped files first or record this attempt as failed."
pause "Live collection and all seven current-run screenshots are ready, or the live run was explicitly blocked? Press Enter for trusted host validation and the structured outcome (stage 6)."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Evidence: host validation, retry loop, and dated structured outcome"
say "The host now checks the mapped copies. Missing evidence triggers a retry; it is never silently accepted. Keep Windows Sandbox open until this validation passes or you deliberately record a failed run."
EVIDENCE_VALIDATED=no
while :; do
  say "The tracked repository helper first re-verifies its own pinned hash, the manifest hash, the read-only kit artifacts, MOTW, and bundled wheel entries before reading any outbox byte."
  if host_helper ValidateCopied; then EVIDENCE_VALIDATED=yes; break; fi
  warn "Trusted host validation rejected incomplete, stale, synthetic, tampered, unbound, undecodable, or wrong-run evidence. Read the failed check above and keep Sandbox open."
  reply=""
  printf '  %s? [r]etry after copying evidence / record this run as [f]ailed / [a]bort and resume later%s ' "$YELLOW" "$RESET"
  read -r reply || true
  case "$reply" in
    f|F) write_env COPIED_EVIDENCE_OK no; break ;;
    a|A) printf '  aborted — do not close Sandbox; re-run %s to resume.\n' "$RUN_COMMAND"; exit 1 ;;
    *) pause "Correct the mapped evidence while Sandbox remains open, then press Enter to validate again." ;;
  esac
done
if [[ "$EVIDENCE_VALIDATED" == yes ]]; then record_check COPIED_EVIDENCE_OK "Did trusted host-validation pass for strict guest JSON, seven decoded/hash-bound PNGs, bound live session/report/marks/notes, and ffprobe-verified source/condensed media?" "Keep Sandbox open, restore every missing mapped item, and rerun trusted host validation."; fi
ask_limitations
REQUIRED_KEYS=(SMARTSCREEN_REPUTATION_OK SMARTSCREEN_SCREENSHOT_OK INSTALL_DIR_OK START_SHORTCUT_OK FIRST_RUN_OK OBS_NOT_FOUND_OK INSTALLED_HELPER_OK HID_FALLBACK_OK MISSING_COMMAND_OK MISSING_EXIT_OK OBS32_OK PYTHON_WHEEL_OK BUNDLED_TOOLS_OK OBS_SETUP_OK MICROPHONE_METER_OK LIVE_DURATION_OK LIVE_MARK_OK LIVE_PIPELINE_OK REPORT_PLAYABLE_OK REPORT_NOTE_OK REPORT_TRANSCRIPT_OK REPORT_SEEK_OK REPORT_MAPPING_OK FIRST_RUN_SCREENSHOT_OK HELPER_SCREENSHOT_OK MISSING_PIPELINE_SCREENSHOT_OK OBS_PREFLIGHT_SCREENSHOT_OK LIVE_PIPELINE_SCREENSHOT_OK LIVE_REPORT_SCREENSHOT_OK INSTALLED_JSON_OK PIPELINE_TOOLS_JSON_OK COLLECTION_JSON_OK COPIED_EVIDENCE_OK)
FINAL_STATUS=PASS
for key in "${REQUIRED_KEYS[@]}"; do [[ "$(state_answer "$key")" == yes ]] || FINAL_STATUS=FAIL; done
OUTCOME_FILE="$(write_outcome "$FINAL_STATUS")"
say "${GREEN}✓${RESET} wrote the dated structured outcome without replacing an earlier outcome: $(to_win "$OUTCOME_FILE")"
if [[ "$FINAL_STATUS" == PASS ]]; then
  say "Every listed release-exit criterion and copied-evidence check passed for this Windows Sandbox run. This records the bounded M5 installer exit result; it does not declare the overall product milestone complete."
else
  warn "Outcome is FAIL because at least one required criterion was failed or missing. Keep the evidence and rerun the wizard after correction; it will preserve this outcome and create a new retry outcome."
fi
if [[ "$(state_answer COPIED_EVIDENCE_OK)" == yes ]]; then
  say "Host validation is complete. You may now close Windows Sandbox; anything needed for the record has been copied to the mapped host folder."
else
  warn "Copied evidence is incomplete. Do not close Windows Sandbox if you intend to recover this run; copy the missing files and rerun the wizard. Closing now means the failed outcome remains and guest-only evidence is lost."
fi
pause "Press Enter to show the wizard summary and exact saved outcome path."

if [[ "$FINAL_STATUS" == PASS ]]; then
  finish
  say "Outcome: $(to_win "$OUTCOME_FILE")"
  say "Run again with: $RUN_COMMAND"
else
  _clear
  printf '\n%s%s  ✗ Release exit recorded as FAIL%s\n\n' "$BOLD" "$RED" "$RESET"
  say "Outcome: $(to_win "$OUTCOME_FILE")"
  say "Correct the recorded failure, keep/copy any recoverable Sandbox evidence, then resume with: $RUN_COMMAND"
  exit 1
fi
