"""YouTube kit (PLAN M2.1, tech-stack §5.0 "Decision 2026-08-23"): a ready-to-
paste `title.txt` + `description.txt` next to `condensed.mp4`, with the video
chapters derived from the notes in CONDENSED time.

YouTube's chapter rules (support.google.com/youtube/answer/9884579): the
first timestamp must be `0:00`, at least three timestamps, ascending, every
chapter at least 10 s long, description at most 5 000 bytes and free of `<`
and `>`. `build_chapters` is a pure function that always satisfies them by
folding notes that land too close together into the previous chapter.
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import Any, Iterable

MIN_CHAPTER_MS = 10_000
MIN_CHAPTERS = 3
TITLE_MAX = 80
YT_TITLE_MAX = 100
DESCRIPTION_MAX_BYTES = 4_800  # YouTube's cap is 5 000; leave room for edits
FOOTER = "Generated by Playtest Recorder"
FEW_CHAPTERS_LINE = "(fewer than 3 chapters — YouTube will not show a chapter bar)"

_SENTENCE_END = re.compile(r"(?<=[.!?])\s+")
_ENUMERATION = re.compile(r"(?:^|\s)\d{1,3}\.$")  # "1." — a list number, not a sentence end
MIN_FIRST_SENTENCE = 24  # keep adding sentences until the title says something


def format_timecode(ms: int) -> str:
    """`m:ss` / `h:mm:ss` — same output as the shared `formatTimecode`."""
    total = max(0, ms) // 1000
    h, rem = divmod(total, 3600)
    m, s = divmod(rem, 60)
    return f"{h}:{m:02d}:{s:02d}" if h else f"{m}:{s:02d}"


def original_to_condensed_ms(cutmap: Iterable[dict[str, Any]], original_ms: int) -> int | None:
    """Port of the shared `originalToCondensedMs`: inside a kept segment →
    shifted; in a gap → start of the next kept segment; after the last → None.
    An empty cut map means the video IS the original (identity)."""
    segments = list(cutmap)
    if not segments:
        return original_ms
    for seg in segments:
        if seg["originalStartMs"] <= original_ms <= seg["originalEndMs"]:
            return seg["condensedStartMs"] + (original_ms - seg["originalStartMs"])
    for seg in segments:
        if seg["originalStartMs"] > original_ms:
            return seg["condensedStartMs"]
    return None


def _clean(text: str) -> str:
    return re.sub(r"\s+", " ", text.replace("<", "(").replace(">", ")")).strip()


def _truncate(text: str, limit: int = TITLE_MAX) -> str:
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "…"


def chapter_title(note: dict[str, Any]) -> str:
    """`LABEL — <first sentence>` (≤ 80 chars, no `<`/`>`); bare `LABEL` when
    the note has no transcribed text."""
    label = _clean(str(note.get("label", "note"))).upper() or "NOTE"
    text = _clean(str(note.get("text") or ""))
    if not text:
        return label
    return _truncate(f"{label} — {first_sentence(text)}")


def first_sentence(text: str) -> str:
    """The first sentence — but an enumeration marker (`1.`) never ends one,
    and very short sentences (`Note.`) pull the next one in so the chapter
    title carries meaning."""
    out = ""
    for piece in _SENTENCE_END.split(text):
        out = f"{out} {piece}".strip()
        if _ENUMERATION.search(out) or len(out) < MIN_FIRST_SENTENCE:
            continue
        break
    return out


def local_day(iso: str) -> str:
    """`YYYY-MM-DD` of an ISO-8601 instant in the machine's local zone (the
    session folder is named by local date too); '' when unparsable."""
    if not iso:
        return ""
    try:
        return datetime.fromisoformat(iso.replace("Z", "+00:00")).astimezone().date().isoformat()
    except ValueError:
        return iso[:10] if len(iso) >= 10 else ""


def build_chapters(
    notes: list[dict[str, Any]],
    cutmap: list[dict[str, Any]],
    condensed_duration_ms: int,
) -> list[tuple[int, str]]:
    """(condensed_ms, title) chapters that satisfy YouTube's rules.

    - notes are mapped to condensed time through the cut map; notes whose
      window was dropped (`None`) are skipped;
    - a chapter always starts at `0:00`, titled after the first note when it
      lands < 10 s in, else `Session start`;
    - a note < 10 s after the previous chapter folds into it (`A · B`), and
      so does a note < 10 s before the end of the video.
    """
    placed: list[tuple[int, str]] = []
    for note in notes:
        ms = original_to_condensed_ms(cutmap, int(note["videoMs"]))
        if ms is None:
            continue
        placed.append((ms, chapter_title(note)))
    placed.sort(key=lambda p: p[0])

    chapters: list[tuple[int, str]] = [(0, "Session start")]
    for ms, title in placed:
        last_ms, last_title = chapters[-1]
        folds = (
            ms - last_ms < MIN_CHAPTER_MS
            or condensed_duration_ms - ms < MIN_CHAPTER_MS
        )
        if folds:
            # A placeholder ("Session start") or a bare label (silent mark) is
            # replaced by a titled note rather than joined to it.
            replace = last_title == "Session start" or (" — " not in last_title and " — " in title)
            merged = title if replace else f"{last_title} · {title}"
            chapters[-1] = (last_ms, _truncate(merged))
        else:
            chapters.append((ms, title))
    return chapters


def chapter_lines(chapters: list[tuple[int, str]]) -> list[str]:
    return [f"{format_timecode(ms)} {title}" for ms, title in chapters]


def build_title(report_data: dict[str, Any]) -> str:
    session = report_data["session"]
    day = local_day(str(session.get("date") or ""))
    title = _clean(str(session.get("title") or session.get("id") or "Playtest"))
    suffix = f" — playtest {day}" if day else " — playtest"
    return _truncate(title, YT_TITLE_MAX - len(suffix)) + suffix


def build_description(report_data: dict[str, Any], max_bytes: int = DESCRIPTION_MAX_BYTES) -> str:
    """Summary line, blank, chapter list, blank, footer — ≤ `max_bytes` UTF-8.
    Chapters beyond the byte budget are dropped, with a pointer to the
    Notion report for the remaining notes."""
    session = report_data["session"]
    video = report_data["video"]
    notes = report_data.get("notes", [])
    cutmap = report_data.get("cutmap", []) if video.get("kind") == "condensed" else []
    chapters = build_chapters(notes, cutmap, int(video["durationMs"]))
    lines = chapter_lines(chapters)

    date = local_day(str(session.get("date") or ""))
    condensed = (
        f"condensed {format_timecode(int(video['durationMs']))}"
        if video.get("kind") == "condensed"
        else f"full recording {format_timecode(int(video['durationMs']))}"
    )
    summary = (
        f"{len(notes)} notes · original {format_timecode(int(session['originalDurationMs']))} · "
        f"{condensed}" + (f" · recorded {date}" if date else "")
    )
    tail = [FEW_CHAPTERS_LINE] if len(chapters) < MIN_CHAPTERS else []

    def assemble(chapter_subset: list[str], extra: list[str]) -> str:
        return "\n".join([summary, "", *chapter_subset, *extra, *tail, "", FOOTER])

    text = assemble(lines, [])
    if len(text.encode("utf-8")) <= max_bytes:
        return text
    kept = len(lines)
    while kept > 1:
        kept -= 1
        dropped = len(chapters) - kept
        text = assemble(lines[:kept], [f"… and {dropped} more notes in the Notion report"])
        if len(text.encode("utf-8")) <= max_bytes:
            return text
    return text


def write_kit(report_dir: Path, report_data: dict[str, Any]) -> Path:
    kit_dir = report_dir / "youtube"
    kit_dir.mkdir(parents=True, exist_ok=True)
    (kit_dir / "title.txt").write_text(build_title(report_data) + "\n", encoding="utf-8")
    (kit_dir / "description.txt").write_text(build_description(report_data) + "\n", encoding="utf-8")
    return kit_dir


def print_kit_instructions(kit_dir: Path, report_dir: Path) -> None:
    print("YouTube kit (unlisted upload is the video carrier for the Notion page):")
    print(f"  {kit_dir}")
    print(f"  1. YouTube Studio → Create → Upload videos → drop {report_dir / 'condensed.mp4'}")
    print("  2. Title from title.txt, paste description.txt (chapters), Visibility: Unlisted,")
    print("     Audience: not made for kids")
    print(f"  3. playtest-notion publish \"{report_dir}\" --youtube https://youtu.be/<id>")
